######################################################################################################################## .
#' @name SimulateMultipleOutcomesCovariatesStratRandomization
#'
#' @title Simulate Multiple Independent Outcomes with Covariate Effects and Stratified Randomization
#'
#' @description This function simulates three independent normally distributed outcomes for a given number of
#'   subjects,
#' incorporating covariate effects. This function performs stratified randomization based on the two covariates:
#'        \itemize{
#'          \item Covariate 1: binary (e.g., diabetic)
#'          \item Covariate 2: binary (e.g., smoker)
#'        }
#' Covariate effects are incorporated linearly into the outcome generation.
#' Note: this function can be extended to simulate any number of endpoints and covariates.
#'
#' @author Julija Saltane
#'
#' @param NumSub Integer number of subjects in the trial.
#'
#' @param ArrivalTime Numeric vector of subject arrival times on the calendar scale, with one element per subject,
#'   in the same order as TreatmentID.
#'
#' @param TreatmentID Integer vector of treatment assignments, with one element per subject: 0 = placebo/control, 1
#'   = first experimental arm, 2 = second experimental arm, and so on.
#'
#' @param Mean Numeric vector of mean responses by arm, with the control arm first, followed by experimental arms
#'   in TreatmentID order.
#'
#' @param StdDev Numeric vector of response standard deviations by arm, with the control arm first, followed by
#'   experimental arms in TreatmentID order.
#'
#' @param UserParam Optional named list of user-defined parameters supplied through East Horizon. The default is
#'   NULL. Access elements by name, for example `UserParam$ParameterName`, rather than by position. User-defined
#'   scalar parameters may be integer, numeric, or character values. Pass the individual named elements to helper
#'   functions so East Horizon can identify and populate the required parameters.
#'
#' Example-specific parameters and requirements:
#' Contains treatment-specific means and covariate parameters:
#'        \describe{
#'          \item{MeanOutcome1Ctrl}{Mean of outcome 1 for control group}
#'          \item{MeanOutcome1Trt}{Mean of outcome 1 for treatment group}
#'          \item{MeanOutcome2Ctrl}{Mean of outcome 2 for control group}
#'          \item{MeanOutcome2Trt}{Mean of outcome 2 for treatment group}
#'          \item{MeanOutcome3Ctrl}{Mean of outcome 3 for control group}
#'          \item{MeanOutcome3Trt}{Mean of outcome 3 for treatment group}
#'          \item{Beta1}{Effect size of covariate 1}
#'          \item{Beta2}{Effect size of covariate 2}
#'          \item{Cov1Prob}{Probability of covariate 1 being 1}
#'          \item{Cov2Prob}{Probability of covariate 2 being 1}
#'          \item{AllocRatio}{Ratio of treatment to control allocation (e.g., 1 for equal allocation, 2 for twice
#'            as many in treatment)}
#'        }
#'
#' @return Named list of supported output elements. Return the fields needed by the chosen analysis or generation
#'   method; additional custom outputs may also be included.
#' \describe{
#'   \item{Response}{Numeric vector of generated subject responses, with one element per subject.}
#'   \item{ErrorCode}{Optional integer execution status: 0 = no error; a positive value aborts the current
#'     simulation but allows subsequent simulations to run; a negative value is fatal and stops all further
#'     simulations.}
#' }
#'
#' Example-specific additional output elements:
#' \describe{
#'   \item{PatientOutcome1}{Numeric vector of simulated values for continuous outcome 1}
#'   \item{PatientOutcome2}{Numeric vector of simulated values for continuous outcome 2}
#'   \item{PatientOutcome3}{Numeric vector of simulated values for continuous outcome 3}
#'   \item{Covariate1}{Binary vector of simulated values for covariate 1}
#'   \item{Covariate2}{Binary vector of simulated values for covariate 2}
#'   \item{PatientTreatmentID}{Optional custom integer vector of treatment assignments: 0 = control; 1 =
#'     treatment. Generated by SimulateMultipleOutcomesCovariatesStratRandomization and used in place of the
#'     native TreatmentID for that example.}
#' }
#'
#' @details Usage of TreatmentID in this example: Integer vector. Not used directly in this function, as stratified
#'   randomization is performed by the function, generating new treatment IDs (0 = control, 1 = treatment).
#'
#' Usage of Mean in this example: Numeric. Not used directly in this function.
#'
#' Usage of StdDev in this example: Numeric. Not used directly in this function.
#'
#' Example-specific error codes: Integer. 0 if successful, 1 if `UserParam` is NULL
######################################################################################################################## .

SimulateMultipleOutcomesCovariatesStratRandomization <- function( NumSub, ArrivalTime, TreatmentID, Mean, StdDev, UserParam = NULL ) {
    # Initialize the return variables that will contain results for 3 normal endpoints
    vPatientOutcome1 <- rep( 0, NumSub ) # First outcome
    vPatientOutcome2 <- rep( 0, NumSub ) # Second outcome
    vPatientOutcome3 <- rep( 0, NumSub ) # Third outcome

    # Validate custom variable input and set defaults
    nErrorCode <- 0

    if ( is.null( UserParam ) ) {
        nErrorCode <- 1
    }

    # Extract means for each outcome and group
    vMeansOutcome1 <- c( UserParam$MeanOutcome1Ctrl, UserParam$MeanOutcome1Trt )
    vMeansOutcome2 <- c( UserParam$MeanOutcome2Ctrl, UserParam$MeanOutcome2Trt )
    vMeansOutcome3 <- c( UserParam$MeanOutcome3Ctrl, UserParam$MeanOutcome3Trt )

    # Extract covariate effects
    dBeta1 <- UserParam$Beta1
    dBeta2 <- UserParam$Beta2

    # Simulate the effect of covariates
    vCovariate1 <- stats::rbinom( NumSub, size = 1, prob = UserParam$Cov1Prob )
    vCovariate2 <- stats::rbinom( NumSub, size = 1, prob = UserParam$Cov2Prob )
    vCovariateEffect <- dBeta1 * vCovariate1 + dBeta2 * vCovariate2

    # Create strata
    vCovariate1Groups <- factor( ifelse( vCovariate1 == 0, "Non-Diabetic", "Diabetic" ), levels = c( "Non-Diabetic", "Diabetic" ) )
    vCovariate2Groups <- factor( ifelse( vCovariate2 == 0, "Non-Smoker", "Smoker" ), levels = c( "Non-Smoker", "Smoker" ) )
    vStrata <- interaction( vCovariate1Groups, vCovariate2Groups, sep = "_" )

    # Create allocation fraction
    vAllocRatio <- c( 1, UserParam$AllocRatio )
    vAllocFraction <- c( vAllocRatio[ 1 ] / sum( vAllocRatio ), 1 - vAllocRatio[ 1 ] / sum( vAllocRatio ) )

    # Randomize treatment within each stratum
    vTreatmentID <- rep( 0, NumSub )

    for ( strStrata in unique( vStrata ) ) {
        # Determine indeces of patients in that strata
        vIndex <- which( vStrata == strStrata )
        nSampleSize <- length( vIndex )

        # Calculate allocation fraction for control and treatment group
        nSampleSizeTrt <- nSampleSize - round( nSampleSize * vAllocFraction[ 1 ] )

        # Find the indices for treatment group
        vTreatmentArmIndex <- vIndex[ sample( 1:nSampleSize, size = nSampleSizeTrt, replace = FALSE ) ]
        vTreatmentID[ vTreatmentArmIndex ] <- 1
    }

    # Simulate the patient independent outcome data
    for ( nPatientIndex in 1:NumSub ) {
        # Convert 0(Ctrl) -> 1 to 1 (Trt) -> 2 for indexing
        nTreatmentID <- vTreatmentID[ nPatientIndex ] + 1

        vPatientOutcome1[ nPatientIndex ] <- stats::rnorm( 1, mean = vMeansOutcome1[ nTreatmentID ] + vCovariateEffect[ nPatientIndex ], sd = 1 )
        vPatientOutcome2[ nPatientIndex ] <- stats::rnorm( 1, mean = vMeansOutcome2[ nTreatmentID ] + vCovariateEffect[ nPatientIndex ], sd = 1 )
        vPatientOutcome3[ nPatientIndex ] <- stats::rnorm( 1, mean = vMeansOutcome3[ nTreatmentID ] + vCovariateEffect[ nPatientIndex ], sd = 1 )
    }

    # Return the simulated outcomes and error code
    lReturn <- list(
        PatientOutcome1 = as.double( vPatientOutcome1 ),
        PatientOutcome2 = as.double( vPatientOutcome2 ),
        PatientOutcome3 = as.double( vPatientOutcome3 ),
        PatientTreatmentID = as.integer( vTreatmentID ),
        Covariate1 = as.double( vCovariate1 ),
        Covariate2 = as.double( vCovariate2 ),
        Response = as.double( rep( 0, NumSub ) ),
        ErrorCode = as.integer( nErrorCode )
    )

    return( lReturn )
}
