#' @name AnalyzeDoseFindingContinuousUsingPairwiseTTest 
#' @title Analyze continuous outcome for dose finding design using Fixed Sequence Pairwise t-test.
#' @param SimData Data frame with subject data generated in current simulation with one row per patient.
#'        It will have headers indicating the names of the columns. These names will be same as those used in
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime,
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of
#'        this data frame. For analysis the most relevant variables are:
#'        \describe
#'        {
#'          \item{ArrivalTime}{A numeric value with the time the patient arrived in the trial}
#'          \item{TreatmentID}{An integer value specifying the index of arms to which subjects are allocated (one arm index per subject). Index for control is 0}
#'          \item{Response}{A numeric value for the continuous endpoint response value.}
#'        }
#' @param DesignParam R List which consists of Design and Simulation Parameters which user
#'      may need to compute test statistic and perform test. User should access the variables
#'      using names for e.g., DesignParam$Alpha and not order. The items are as follows:
#'      \describe{
#'          \item{NumTreatments}{Integer. Number of Treatment arms (excluding control)}
#'          \item{Alpha}{Numeric. Type I Error (one-sided significance level)}
#'          \item{TailType}{Integer. Values are Left Tailed: 0, Right Tailed: 1}
#'          \item{VarType}{Integer. Variance Type. Values are Equal/Pooled: 4, Unequal/Welch: 5}
#'          \item{IsArmPresent}{Vector of integer flags indicating whether an arm is still present in the trial or was dropped in the interim. Length = number of treatment arms. Values are - Dropped in the interim: 0, Still present in the trial: 1}
#'          \item{MultAdjMethod}{Integer. Multiple Comparison Procedure. Values are Fixed Sequence Pairwise: 8}
#'          \item{RespLag}{Numeric. Follow up duration (optional)}
#'      }
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic
#'                 and perform test. User should access the variables using names,
#'                 for example LookInfo$nNumLooks and not order. Other important variables are:
#'                 \describe{
#'                      \item{NumLooks}{An integer value with the number of looks in the study.}
#'                      \item{CurrLookIndex}{An integer value with the current index look, starting from 1.}
#'                      \item{CumCompleters}{Vector of Cumulative number of completers. Length = Number of looks.}
#'                      \item{FutBdryScale}{Integer. Futility boundary scale. Values are: vDelta: 2, Isotonic vDelta: 4}
#'                      \item{FutBdry}{Vector of numeric futility boundaries. Length = Number of looks. Can be NA.}
#'                      \item{PoCScale}{Integer. Proof of Concept scale. Values are High Dose vs. Control: 0}
#'                      \item{PoCThreshold}{Numeric scalar. Proof of Concept threshold value.}
#' }
#' @param OutList List or NULL. Pass-through list from previous look (for multi-look tracking).
#'        Engine sets this to NULL for the first look. Supports Numeric/Integer/Character/List.
#'        Optional.
#' @param UserParam User can pass custom scalar variables defined by users as a member of this list.
#'                  User should access the variables using names, for example UserParam$Var1 and not order.
#'                  These variables can be of the following types: Integer, Numeric, or Character.
#'                  Optional.
#' @return The function must return a list in the return statement of the function. The information below lists
#'             elements of the list, if the element is required or optional and a description of the return values if needed.
#'             \describe{
#'                  \item{Decision}{Vector of Integers or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Mandatory value. Values have the following meaning:
#'                                  \describe{
#'                                    \item{Decision = NA}{When the arm is dropped in a previous look}
#'                                    \item{Decision = 0}{when No boundary, futility or efficacy is crossed}
#'                                    \item{Decision = 1}{when the Lower Efficacy Boundary Crossed}
#'                                    \item{Decision = 2}{when the Upper Efficacy Boundary Crossed}
#'                                    \item{Decision = 3}{when the Futility Boundary Crossed}
#'                                    }
#'                                    }
#'                  \item{RawPVal}{p-Value computed from test statistics. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value.}
#'                  \item{TestStat}{Value of appropriate Test Statistic on Wald (Z) scale for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value.}
#'                  \item{Delta}{Estimate of vDelta (Difference from Control) for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Conditionally Mandatory if nFutBdryScale = 2 or 4.}
#'                  \item{POCStatusArm}{Per-arm Proof of Concept status. Vector of Integers (0 or 1) having length the same as number of treatment arms. 1 = PoC threshold crossed for this arm, 0 = not crossed. Optional - Dose Finding only.}
#'                  \item{POCStatus}{Overall Proof of Concept status. Integer scalar (0 or 1). 1 = PoC threshold crossed overall, 0 = not crossed. Determined by highest dose arm. Optional - Dose Finding only.}
#'                  \item{AnalysisTime}{Optional Numeric scalar. Estimate of Analysis time. Same as look time for interims. Same as study duration for the final analysis.}
#'                  \item{OutList}{List or NULL. Pass-through list to next look for multi-look tracking. Optional.}
#'                  \item{ErrorCode}{Integer. Optional value \describe{
#'                                     \item{ErrorCode = 0}{No Error}
#'                                     \item{ErrorCode > 0}{Nonfatal error, current simulation is aborted but the next simulations will run}
#'                                     \item{ErrorCode < 0}{Fatal error, no further simulation will be attempted}
#'                                     }
#'                                     }
#'                      }
#' @details
#' This function implements Fixed Sequence Pairwise testing for dose-finding studies with continuous endpoints.
#' The Fixed Sequence gatekeeping procedure tests hypotheses sequentially from the highest dose downward,
#' rejecting the null hypothesis only if the raw p-value is less than the total alpha. Once a hypothesis fails
#' to reject, all lower dose hypotheses are automatically rejected (futility cascade).
#' @export
AnalyzeDoseFindingContinuousUsingPairwiseTTest <- function( SimData, DesignParam, LookInfo, OutList, UserParam = NULL )
{
  nErrorCode      <- 0L
  
  # Reading inputs ####
  # Extracting parameters from DesignParam 
  nNumTrt         <- DesignParam$NumTreatments
  dTotalAlpha     <- DesignParam$Alpha
  nTailType       <- DesignParam$TailType
  nVarType        <- DesignParam$VarType
  bIsArmPresent   <- DesignParam$IsArmPresent
  # Extracting parameters from LookInfo
  nNumLooks       <- LookInfo$NumLooks
  nCurrLookIndex  <- LookInfo$CurrLookIndex
  nFutBdryScale   <- LookInfo$FutBdryScale
  vFutBdry        <- LookInfo$FutBdry
  nPoCScale       <- LookInfo$PoCScale
  dPoCThreshold   <- LookInfo$PoCThreshold
  vCumCompleters  <- LookInfo$CumCompleters
  
  # Initializing output vectors ####
  # Decision vector: NA = dropped, 0 = no boundary, 1 = lower eff, 2 = upper eff, 3 = futility
  vDecision         <- rep( 0L, nNumTrt )
  vRawPVal          <- rep( NA_real_, nNumTrt )
  vTestStat         <- rep( NA_real_, nNumTrt )
  vDelta            <- rep( NA_real_, nNumTrt )
  vIsoDelta         <- rep( NA_real_, nNumTrt )
  # PoC status vectors
  vPOCStatusArm     <- rep( 0.0, nNumTrt )
  dOverallPOC       <- 0.0
  
  # Setting decision of earlier dropped arms/doses as NA
  vDecision[ bIsArmPresent == 0 ] <-  NA_integer_
  # Reading PoC status of the last look
  if( nCurrLookIndex > 1 ) 
  {
    vPOCStatusArm                   <- OutList$vPOCStatusArm
    dOverallPOC                     <- OutList$dOverallPOC
  }  
    
  # Compute Analysis Time ####
  dEstAnalysisTime  <- ComputeAnalysisTime( dRespLag = DesignParam$dRespLag, vArrivalTime = SimData$ArrivalTime, 
                                           vCumCompleters = vCumCompleters, nCurrLookIndex = nCurrLookIndex ) 
  
  # Prepare data ###
  dfSimData         <- SimData[ with( SimData, ClndrRespTime  <= dEstAnalysisTime & CensorIndOrg == 1) , ]
  
  # Compute Summary ####
  # Identify active and dropped arms
  vSelectedArmIndex <- which( bIsArmPresent == 1 )
  nNumActive        <- length( vSelectedArmIndex )
  vDroppedArms      <- which( bIsArmPresent == 0 )
  
  vRespCtrl         <- dfSimData$Response[ dfSimData$TreatmentID == 0 ]
  nNumCtrl          <- length( vRespCtrl )
  dMeanRespCtrl     <- mean( vRespCtrl )
  dVarRespCtrl      <- var( vRespCtrl )
  vNumTrt           <- rep( NA_real_, nNumActive )
  vMeanRespTrt      <- rep( NA_real_, nNumActive )
  vVarRespTrt       <- rep( NA_real_, nNumActive )  
  vDeltaEst         <- rep( NA_real_, nNumActive )
  
  for( nArmNum in seq_along( vSelectedArmIndex ) ) 
  {
    nTrtArmIndex            <- vSelectedArmIndex[ nArmNum ]
    vRespTrt                <- dfSimData$Response[ dfSimData$TreatmentID == nTrtArmIndex ]
    vNumTrt[ nArmNum ]      <- length( vRespTrt )
    vMeanRespTrt[ nArmNum ] <- mean( vRespTrt ) 
    vVarRespTrt[ nArmNum ]  <- var( vRespTrt )
    vDeltaEst[ nArmNum ]    <- vMeanRespTrt[ nArmNum ] - dMeanRespCtrl
  }
  # Compute isotonic deltas: enforce monotonicity on deltas
  vIsoDelta[ vSelectedArmIndex ] <- ComputeIsotonicDeltas( vDeltaEst, nTailType )

  # Proof of Concept Assessment ####
  if( !is.null( dPoCThreshold ) && !is.na( dPoCThreshold ) ) 
  {
    vActiveForPoC   <- which( !is.na( vIsoDelta ) )
    if( length( vActiveForPoC ) > 0 ) 
    {
      # PoC: independent per-arm check for Pairwise test
      if( nTailType == 1L ) {
        # Right-Tail: PoC if delta > threshold
        vArmWithPOC <- which( round( vIsoDelta[ vSelectedArmIndex ], 7 ) > dPoCThreshold )
        
      } else {
        # Left-Tail: PoC if delta < threshold
        vArmWithPOC <- which( round( vIsoDelta[ vSelectedArmIndex ], 7 ) < dPoCThreshold )
      }
      vPOCStatusArm[ vSelectedArmIndex[ vArmWithPOC ] ] <- 1
      
      # Overall PoC: determined by highest dose arm (i.e. last treatment arm)
      dOverallPOC   <- ifelse( vPOCStatusArm[ max( vSelectedArmIndex ) ] == 1, 1, 0)
    }
  }
  

  # Check for Futility in interims using isotonic delta ####
  bTestFutility     <- !is.null( vFutBdry ) && !is.na( vFutBdry[ nCurrLookIndex] ) && nCurrLookIndex < nNumLooks
  if( bTestFutility ) 
  {
    dFutBdryVal     <- vFutBdry[ nCurrLookIndex ]

    # vDelta Scale: compare delta estimate against futility boundary
    if( nTailType == 1L ) {
      vDecision[ vSelectedArmIndex ] <- as.numeric( vIsoDelta[ vSelectedArmIndex ] < dFutBdryVal ) * 3
    } else {
      vDecision[ vSelectedArmIndex ] <- as.numeric( vIsoDelta[ vSelectedArmIndex ] > dFutBdryVal ) * 3 
    }
  }      

  
  # Testing for efficacy at the last look #### 
  if( nCurrLookIndex == nNumLooks &&  nNumActive > 0 )
  {
    # Compute variance and degrees of freedom
    if( nVarType == 4L ) 
    {
      # Equal variance: pooled
      vSp2    <- ( ( nNumCtrl - 1 ) * dVarRespCtrl + ( vNumTrt - 1 ) * vVarRespTrt ) / ( nNumCtrl + vNumTrt - 2 )
      vSE     <- sqrt( vSp2 * ( 1 / nNumCtrl + 1 / vNumTrt ) )
      vDOF    <- nNumCtrl + vNumTrt - 2
    } else {
      # Unequal variance: Welch
      dSEC    <- dVarRespCtrl / nNumCtrl
      vSET    <- vVarRespTrt / vNumTrt
      vSE     <- sqrt( dSEC + vSET )
      vDOF    <- round( ( dSEC + vSET )^2 / ( dSEC^2 / ( nNumCtrl - 1 ) + vSET^2 / ( vNumTrt - 1 ) ) )
    }

    # Compute test statistic and p-value
    vTestStat[ vSelectedArmIndex ]  <- vIsoDelta[ vSelectedArmIndex ] / vSE

    if( nTailType == 1L ) 
    {
      # Right-Tail: P(T > dTstat)
      vRawPVal[ vSelectedArmIndex ] <- pt( vTestStat[ vSelectedArmIndex ], df = vDOF, lower.tail = FALSE )
    } else { 
      # Left-Tail: P(T < dTstat)
      vRawPVal[ vSelectedArmIndex ] <- pt( vTestStat[ vSelectedArmIndex ], df = vDOF, lower.tail = TRUE )
    }

    lTestResults <-  ApplyFixedSeqPairwiseTest( vRawPValues = vRawPVal [ vSelectedArmIndex ], 
                                                vDoseSequence = nNumActive:1, 
                                                dAlpha =  dTotalAlpha )
    if( nTailType == 0)
    {
      lTestResults$vDecision <- as.integer( lTestResults$vDecision * 1 )
    } else {
      lTestResults$vDecision <- as.integer( lTestResults$vDecision * 2 )
    }

    vDecision[ vSelectedArmIndex ]  <- lTestResults$vDecision
    vDecision[ vDecision == 0 ]     <- 3 # Setting all the non-concluded hypotheses as futile
  }
  
  # Prepare OutList for next look ####
  lNewOutList <- list( vPOCStatusArm  = vPOCStatusArm, dOverallPOC    = dOverallPOC)
  
  # Return Results ####
  return( list( Decision     = as.integer( vDecision ),
                RawPVal      = as.double( vRawPVal ),
                TestStat     = as.double( vTestStat ),
                Delta        = as.double( vIsoDelta ),
                POCStatusArm = as.integer( vPOCStatusArm ),
                POCStatus    = as.integer( dOverallPOC ),
                AnalysisTime = as.double( dEstAnalysisTime ),
                OutList      = lNewOutList,
                ErrorCode    = as.integer( nErrorCode ) ) )
}


# HELPER FUNCTION: Analysis Time Computation ####
ComputeAnalysisTime <- function( dRespLag, vArrivalTime, vCumCompleters, nCurrLookIndex )
{
  dRespLag            <- ifelse( !is.null( dRespLag ), dRespLag, 0 )
  dCompletionTimes    <- sort( vArrivalTime + dRespLag )
  nTargetCompleters   <- vCumCompleters[ nCurrLookIndex ]
  
  if( !is.null( nTargetCompleters ) &&
      !is.na( nTargetCompleters ) &&
      nTargetCompleters <= length( dCompletionTimes ) ) 
  {
    dEstAnalysisTime  <- dCompletionTimes[ nTargetCompleters ]
  } else {
    dEstAnalysisTime  <- max( dCompletionTimes, na.rm = TRUE )
  }
  return( dEstAnalysisTime )
}


# HELPER FUNCTION: Isotonic Regression via PAVA ####
# Computes isotonic regression to enforce monotonicity on values using
# the Pool Adjacent Violators Algorithm (PAVA).
# 
# Inputs:
# numeric vector of values to be monotonized
# tail type:  0 = left-tail, 1 = right-tail
#
# Output:
# numeric vector of isotonic values (same length as input)
ComputeIsotonicDeltas <- function( vValues, nTailType )
{
  n <- length( vValues )
  if( n == 0 ) return( numeric(0) )
  
  # For non-increasing (left-tail), negate values
  if( nTailType == 0L ) vValues <- -vValues
  
  vBlockVal <- vValues
  vBlockIdx <- as.list( 1:n )
  
  repeat {
    bMerged <- FALSE
    i <- 1
    while( i < length( vBlockVal ) ) {
      if( vBlockVal[ i ] > vBlockVal[ i + 1 ] ) {
        # Merge blocks i and i+1 with simple average
        dNewVal         <- mean( c( vBlockVal[ i ], vBlockVal[ i + 1 ] ) )
        vBlockVal[i]    <- dNewVal
        vBlockVal       <- vBlockVal[ -( i + 1 ) ]
        vBlockIdx[[i]]  <- c( vBlockIdx[[ i ]], vBlockIdx[[ i + 1 ]] )
        vBlockIdx       <- vBlockIdx[ -( i + 1 ) ]
        bMerged         <- TRUE
      } else {
        i               <- i + 1
      }
    }
    if( !bMerged ) break
  }
  
  # Reconstruct result vector
  vResult <- numeric( n )
  for( j in seq_along(vBlockVal ) ) {
    vResult[ vBlockIdx[[j]] ]     <- vBlockVal[ j ]
  }
  
  # Negate back if left-tail
  if( nTailType == 0L ) vResult  <- -vResult
  
  return( vResult )
}

# HELPER FUNCTION: Fixed Sequence Pairwise Test #####
# Example : MCP_Method = Fixed Sequence
#
# Inputs:
#   Vector of raw P values
#   Sequence of treatment arms by Dose (1: Highest Dose, n : Lowest Dose)
#   Alpha (Type I error)
# Output:
#   Vector of adjusted P values
#   global adjusted P-value
#   Decision
ApplyFixedSeqPairwiseTest <- function( vRawPValues, vDoseSequence, dAlpha ) {
  # Input validation
  if( length( vRawPValues ) != length( vDoseSequence ) ) {
    stop("Length of vRawPValues and vDoseSequence must be equal")
  }
  
  # Step 1: Order p-values according to sequence
  vOrdRawPValues  <- vRawPValues[ order( vDoseSequence ) ]
  
  # Step 2: Compute adjusted p-values for each hypothesis
  vAdjPValues     <- cummax( vOrdRawPValues )
  
  # Step 3: Compute adjusted p-value for global null hypothesis
  dAdjPValGlobal  <- vOrdRawPValues[ 1 ]
  
  # Step 4: Rearrange adjusted p-values and decisions back to original order
  vIdxOrder       <- order( vDoseSequence )
  vAdjPValues     <- vAdjPValues[ order( vIdxOrder ) ]
  
  return( list( vAdjPValues = vAdjPValues,
                dAdjPValGlobal = dAdjPValGlobal,
                vDecision = (vAdjPValues < dAlpha ) ) )
}