---
title: "Examples Outline"
author: "J. Kyle Wathen, Gabriel Potvin"
date:  "`r format(Sys.time(), '%B %d, %Y')`"
output:
  word_document: default
  html_document: default
---

## Introduction

This document provides an overview of the R examples provided in [this directory](https://github.com/Cytel-Inc/CyneRgy/tree/main/inst/Examples). Each example is included in a directory that provides:

- an RStudio project file, 
- a Description file that describes the example, 
- an R folder which contains the example R scripts,
- optional: a FillInTheBlankR folder which contains the worked examples with various code deleted so you can practice and fill in the blanks. 

The following examples are included:

## Enrollment

<details>
<summary>**Arrival Times with Poisson Process**
<span class="badge text-bg-primary ms-1">Any # of Arms</span><span class="badge text-bg-danger ms-1">Any # of Endpoints</span><span class="badge text-bg-warning ms-1">Any Outcome</span></summary>
This example demonstrates how to add the ability to generate patient arrival times according to a Poisson process with a ramp-up by customizing the Enrollment integration point of East Horizon.  
[Click here to view the full example.](GeneratePoissonArrival.html)
</details>

---

## Randomization

<details>
<summary>**Randomization of Subjects**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Any Outcome</span></summary>
This example illustrates three ways to customize how subjects are assigned to treatment arms in East Horizon: using a uniform distribution, using the `sample()` function, and using the `randomizeR` package.
[Click here to view the full example.](PatientRandomization.html)
</details>

The description for the Multiple Arm example is not available yet, but the example can be found [here](https://github.com/Cytel-Inc/CyneRgy/blob/main/inst/Examples/RandomizeSubjects/R/RandomizeSubjectsAcrossMultipleArms.R).

---

## Dropout

<details>
<summary>**Simulate Patient Dropout**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Any # of Endpoints</span><span class="badge text-bg-warning ms-1">Any Outcome</span></summary>
This example illustrates how to customize the dropout distribution in East Horizon for continuous and binary outcomes, time-to-event outcome, and continuous outcome with repeated measures.
[Click here to view the full example.](PatientDropout.html)
</details>

Descriptions for the Multiple Arm examples are not available yet, but the examples can be found in [this folder](https://github.com/Cytel-Inc/CyneRgy/blob/main/inst/Examples/MultiArmPatientDropout/R/).

---

## Response (Patient Simulation)

<details>
<summary>**Continuous Outcome – Patient Simulation**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span></summary>
This example demonstrates two ways to customize the patient outcome simulation in East Horizon for a two-arm trial with a continuous outcome: using a mixture distribution, with or without the mixture proportion sampled from a Beta distribution.  
[Click here to view the full example.](2ArmNormalOutcomePatientSimulationDescription.html)
</details>

<details>
<summary>**Time-To-Event Outcome – Patient Simulation**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">TTE</span></summary>
This example demonstrates two ways to customize the patient outcome simulation in East Horizon for a two-arm trial with a time-to-event outcome: using a Weibull distribution, and using a mixture of exponential distributions.
[Click here to view the full example.](2ArmTimeToEventOutcomePatientSimulationDescription.html)
</details>

<details>
<summary>**Binary Outcome – Patient Simulation**<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Binary</span></summary>
This example demonstrates two ways to customize the patient outcome simulation in East Horizon for a two-arm trial with a binary outcome: using a mixture distribution, with or without the mixture proportion sampled from a Beta distribution. 
[Click here to view the full example.](2ArmBinaryOutcomePatientSimulation.html)
</details>

<details>
<summary>**Repeated Measures – Patient Simulation**<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Repeated Measures</span></summary>
This example demonstrates how to customize the patient outcome simulation in East Horizon for a two-arm trial with a continuous outcome with repeated measures using the `MASS::mvrnorm()` function.
[Click here to view the full example.](2ArmNormalRepeatedMeasuresResponseGeneration.html)
</details>

<details>
<summary>**Childhood Anxiety Trial**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example covers a specific situation where the patient data simulation needs to be customized to match what is expected in a clinical trial in childhood anxiety.  
[Click here to view the full example.](ChildhoodAnxiety.html)
</details>

Descriptions for the Multiple Arm examples are not available yet, but the examples can be found in [this folder](https://github.com/Cytel-Inc/CyneRgy/blob/main/inst/Examples/MultiArmOutcomePatientSimulation/). Similarly, examples for Dual Endpoints can be found in [this folder](https://github.com/Cytel-Inc/CyneRgy/blob/main/inst/Examples/DEPOutcomePatientSimulation/).

---

## Analysis (Test Statistic)

<details>
<summary>**Continuous Outcome – Analysis**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span></summary>
This example demonstrates three ways to customize the statistical test in East Horizon for a two-arm trial with a continuous outcome: using a formula from the East manual, using the `t.test()` function, and using confidence interval limits for Go/No-Go decision-making. 
[Click here to view the full example.](2ArmNormalOutcomeAnalysisDescription.html)
</details>

<details>
<summary>**Time-To-Event Outcome – Analysis**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">TTE</span></summary>
This example demonstrates three ways to customize the statistical test in East Horizon for a two-arm trial with a time-to-event outcome: using formulas from the East manual, using the `survival::survdiff()` function, and using confidence interval limits for Go/No-Go decision-making. 
[Click here to view the full example.](2ArmTimeToEventOutcomeAnalysisDescription.html)
</details>

<details>
<summary>**Binary Outcome – Analysis**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Binary</span></summary>
This example demonstrates four ways to customize the statistical test in East Horizon for a two-arm trial with a binary outcome: using a formula from the East manual, using the `prop.test()` function, using confidence interval limits for Go/No-Go decision-making, and using a Bayesian Beta-Binomial model.
[Click here to view the full example.](2ArmBinaryOutcomeAnalysisDescription.html)
</details>

<details>
<summary>**Weighted Conditional Power Analysis**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">TTE</span><span class="badge text-bg-secondary ms-1">Design</span></summary>
This example demonstrates how to customize the statistical test in East Horizon for a two-arm trial with a time-to-event outcome using conditional power and futility boundaries based on the Logrank test.
[Click here to view the full example.](TimeToEventConditionalPowerFutilityAnalysis.html)
</details>

Descriptions for the Multiple Arm examples are not available yet, but the examples can be found in [this folder](https://github.com/Cytel-Inc/CyneRgy/blob/main/inst/Examples/MultiArmOutcomeAnalysis/). Similarly, examples for Dual Endpoints can be found in [this folder](https://github.com/Cytel-Inc/CyneRgy/blob/main/inst/Examples/DEPOutcomeAnalysis/) and an example for 2-Arm Repeated Measures can be found [here](https://github.com/Cytel-Inc/CyneRgy/tree/main/inst/Examples/2ArmNormalRepeatedMeasuresOutcomeAnalysis/R).

---

## Treatment Selection

<details>
<summary>**Binary Outcome - Treatment Selection**
<span class="badge text-bg-primary ms-1">Multiple Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Binary</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates four ways to customize the treatment selection in East Horizon for a multiple arm trial: based on response rates, based on p-value, based on number of responses, and based on Bayesian posterior probabilities.
[Click here to view the full example.](TreatmentSelectionDescription.html)
</details>

---

## Advanced Examples

These examples use more than one integration point in the same project to achieve a more complex design option.

<details>
<summary>**Bayesian Assurance, Continuous**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates the computation of Bayesian assurance, or probability of success, using a mixture of normal distribution priors featuring a two-arm trial with continuous outcome.  
[Click here to view the full example.](BayesianAssuranceContinuous.html)
</details>

<details>
<summary>**Bayesian Assurance, Time-to-Event**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">TTE</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates the computation of Bayesian assurance, or probability of success, using a bi-modal distribution prior featuring a two-arm trial with time-to-event outcome.  
[Click here to view the full example.](BayesianAssuranceTimeToEvent.html)
</details>

<details>
<summary>**Consecutive Studies, Binary**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Binary</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates the computation of conditional probability of success in consecutive studies. It features a sequential design involving a Phase 2 trial followed by a Phase 3 trial, both with a binary outcome Phase 2 results are saved and then used as the prior for Phase 3, allowing Phase 3 patient outcomes to be generated conditional on Phase 2 success.  
[Click here to view the full example.](ConsecutiveStudiesBinary.html)
</details>

<details>
<summary>**Consecutive Studies, Continuous**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates the computation of Bayesian assurance, or probability of success, in consecutive studies: a Phase 2 trial followed by a Phase 3 trial, both with continuous outcome. The objective is to understand how conducting a Phase 2 study can reduce the risk associated with the Phase 3 trial.  
[Click here to view the full example.](ConsecutiveStudiesContinuous.html)
</details>

<details>
<summary>**Consecutive Studies, Continuous & TTE**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span><span class="badge text-bg-warning ms-1">TTE</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates the computation of Bayesian assurance, or probability of success, in consecutive studies: a Phase 2 trial with continuous outcome followed by a Phase 3 trial with time-to-event outcome. The objective is to understand how conducting a Phase 2 study can reduce the risk associated with the Phase 3 trial. This example also includes a step to load the Phase 2 output and extract the true treatment differences.  
[Click here to view the full example.](ConsecutiveStudiesContinuousTimeToEvent.html)
</details>

<details>
<summary>**Probability of Success, PFS and OS**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">TTE</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates how to compute the probability of success of a trial and extend East Horizon's single-endpoint framework to handle dual endpoints (Progression-Free Survival and Overall Survival) using custom R scripts for the Analysis and Response integration points.  
[Click here to view the full example.](ProbabilitySuccessDualEndpoints.html)
</details>

<details>
<summary>**Multiple Endpoints, Covariates, Stratified Randomization**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Continuous</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates how to integrate patient outcome simulation and analysis functionality for multiple independent continuous outcomes into East Horizon, across three cases: multiple endpoints using a t-test, multiple endpoints with covariates using ANCOVA, and multiple endpoints with covariates and stratified randomization.
[Click here to view the full example.](MultipleEndpointsWithCovariates.html)
</details>

<details>
<summary>**Schizophrenia Trial (MMRM Analysis)**
<span class="badge text-bg-primary ms-1">2-Arm</span><span class="badge text-bg-danger ms-1">Single Endpoint</span><span class="badge text-bg-warning ms-1">Repeated Measures</span><span class="badge text-bg-secondary ms-1">Explore</span></summary>
This example demonstrates how to simulate and analyze data using a Mixed Model for Repeated Measures (MMRM) approach in the context of a schizophrenia trial.
[Click here to view the full example.](SchizophreniaTrial.html)
</details>
