---
title: "Getting Started"
author: "Gabriel Potvin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

<style>
.button-container {
    text-align: center;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    column-gap: 15px;
}
.btn i {
    margin-right: 5px;
}
</style>

# Overview

Cytel's products such as East Horizon support the customization of trial design simulations by integrating your own R scripts. This feature allows you to leverage R's robust statistical computing capabilities to enhance your simulation designs. This section provides the steps to access the R integration points, input values you can use in your scripts, expected output values, examples and templates. Each integration point provides a set of inputs for use in your R scripts, leaving it up to you to determine if and how they should be utilized.

## Detailed Information on Integration Points

For comprehensive details about each integration point, please refer to the following pages:

:::: {.button-container}
<a href="IntegrationPointInitialization.html" class="btn btn-primary"><i class="fas fa-cogs"></i>Initialization</a>

<a href="IntegrationPointAnalysis.html" class="btn btn-primary"><i class="fas fa-chart-bar"></i>Analysis (Test Statistic)</a>

<a href="IntegrationPointEnrollment.html" class="btn btn-primary"><i class="fas fa-user-clock"></i>Enrollment (Arrival Times)</a>

<a href="IntegrationPointRandomization.html" class="btn btn-primary"><i class="fas fa-random"></i>Randomization (Assignment of Subjects)</a>

<a href="IntegrationPointResponse.html" class="btn btn-primary"><i class="fas fa-user-md"></i>Response (Patient Simulation)</a>

<a href="IntegrationPointDropout.html" class="btn btn-primary"><i class="fas fa-user-slash"></i>Dropout</a>

<a href="IntegrationPointTreatmentSelection.html" class="btn btn-primary"><i class="fas fa-project-diagram"></i>Treatment Selection</a>

<a href="IntegrationPointMultiplicityAdjustment.html" class="btn btn-primary"><i class="fas fa-calculator"></i>Multiplicity Adjustment</a>

::::

## Additional Resources

For tips, best practices, and further information, visit the following pages on the Cytel Knowledge Base:

### East Horizon

- [Using R functions within East Horizon: Explore](https://knowledge.cytel.com/r-connection) <span class="badge text-bg-secondary">For Cytel users only.</span>
- [Pre-installed R packages within East Horizon](https://knowledge.cytel.com/pre-installed-r-packages-within-east-horizon) <span class="badge text-bg-secondary">For Cytel users only.</span>
- [R Code Assistant](https://knowledge.cytel.com/r-code-assistant) <span class="badge text-bg-secondary">For Cytel users only.</span>

### East Desktop

- [R Integration in East](https://knowledge.cytel.com/r-integration-east)
- [R Connection Additional Help: East User Manual Appendix O](https://knowledge.cytel.com/r-connect-additional-help-east-user-manual-chapter-o) <span class="badge text-bg-secondary">For Cytel users only.</span>
