---
title: "Variables of AdaptInfo"
author: "Gabriel Potvin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

The variables in AdaptInfo define the sample size re-estimation design parameters. They can be used in custom scripts for the [Analysis Integration Point](IntegrationPointAnalysis.html) and the [Treatment Selection Integration Point](IntegrationPointTreatmentSelection.html). To access these parameters in your R code, use the syntax: `AdaptInfo$NameOfTheVariable`, replacing `NameOfTheVariable` with the appropriate parameter name.

The tables below describe each variable and notes any conditions under which it can or cannot be used in a project on East Horizon Explore and East Horizon Design. Availability notes are only specified when they differ from the default availability of the integration points (see the pages linked above for details).

AdaptInfo is only available for `Statistical Design = Group Sequential with Sample Size Re-Estimation` (for Design, `Adaptation Method = Cui, Hung, and Wang (CHW) or Chen, DeMets, and Lan (CDL)`. Not available for `Endpoint Type = Continuous with Repeated Measures or Dual Endpoint (TTE-TTE or TTE-Binary)` or `Study Objective = Multiple Arm COnfirmatory`.

# For `Study Objective = Two Arm Confirmatory`

## For `Endpoint Type = Continuous, Binary, Time-to-Event`

|**Variable**|**Type**|**Description**|**Notes**|
|-|-|----|-----|
|**AdaptMethod**|Integer|Adaptation method:<br>- `1`: Cui, Hung, and Wang (CHW).<br>- `2`: Chen, DeMets, and Lan (CDL).||
|**AdaptInterimScale**|Integer|Adapt at interim analysis scale:<br>- `1`: Interim analysis number.<br>- `2`: Analysis spacing info (%).|Fixed to `1` for East Horizon Explore and for `AdaptMethod = 2 (CDL)`.|
|**AdaptInterimNum**|Integer|Interim analysis number at which adaptation will happen.|Fixed to `LookInfo$NumLooks - 1` for `AdaptMethod = 2 (CDL)`.|
|**AdaptInterimPerc**|Integer|Analysis spacing info (%) at which adaptation will happen.|Available only for `AdaptMethod = 2 (CDL)`.|
|**StudyDurationUL**|Numeric|Upper limit on study duration.|Not available for East Horizon Explore.|
|**WaldCPThreshold**|Numeric|Threshold beyond which Wald statistics are used.|Available only for `AdaptMethod = 2 (CDL)`.|
|**EnrollAdaptScale**|Integer|Scale for enrollment rate after adaptation:<br>- `0`: No change.<br>- `1`: Use multiplier.<br>- `2`: Use fixed rate.|`EnrollAdaptScale = 2 (fixed rate)` is only applicable for East Horizon Design.|
|**EnrollAdaptMult**|Numeric|Multiplier for enrollment rate after adaptation.|Available only for `EnrollAdaptScale = 1 (use multiplier)`.|
|**EnrollAdaptRate**|Numeric|Fixed enrollment rate after adaptation.|Available only for `EnrollAdaptScale = 2 (use fixed rate)`.|
|**PromZoneScale**|Integer|Promising zone scale:<br>- `0`: Estimated conditional power.<br>- `1`: Arbitrary/design conditional power.<br>- `2`: Test statistic.<br>- `3`: Estimated delta/sigma.||
|**PromZoneSigma**|Numeric|Reference/design sigma for computing promising zone conditional power.|Available only when `PromZoneScale = 1 (Arbitrary/design conditional power)`.|
|**PromZoneDelta**|Numeric|Reference/design delta for computing promising zone conditional power.|Available only when `PromZoneScale = 1 (Arbitrary/design conditional power)`.|
|**PromZoneMin**|Numeric|Minimum threshold for promising zone.||
|**PromZoneMax**|Numeric|Maximum threshold for promising zone.||
|**SSRFuncScale**|Numeric|Sample size re-estimation function scale for promising zone:<br>- `0`: Continuous.<br>- `1`: Step.<br>- `2`: User-specified R.|`SSRFuncScale = 1 (step)` is available only in East Horizon Explore.|
|**NumSteps**|Integer|Number of steps.|Available only for `SSRFuncScale = 1 (step)`.|
|**MaxSSMultInp**|Named List|Maximum sample size multiplier inputs.|If `SSRFuncScale = 0 (continuous)`, it is a Named List of Numeric:<br>- `MaxSSMultInp[“From”] = PromZoneMin`.<br>- `MaxSSMultInp[“To”] = PromZoneMax`.<br>- `MaxSSMultInp[“MaxSSMult”]` is a numeric specified by the user.<br>If `SSRFuncScale = 1 (step)`, it is a Named List of Array of Numeric:<br>- `MaxSSMultInp[“From”]` is an array of size `NumSteps` containing the lower threshold for each step.<br>- `MaxSSMultInp[“To”]` is an array of size `NumSteps` containing the upper threshold for each step.<br>- `MaxSSMultInp[“MaxSSMult”]` is an array of size `NumSteps` containing the maximum sample size multiplier for each step.|
|**TargetCP**|Numeric|Target conditional power.|Available only for `SSRFuncScale = 0 (continuous)`.|
|**OrigCP**|Numeric|Conditional power computed from the maximum number of completers/events.||
