---
title: "Variables of SimData"
author: "Gabriel Potvin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

# Variables of SimData

The variables in SimData are created during data generation and depend on the current simulation. It stores outputs produced by integration points such as response, enrollment, dropout, or randomization. Any optional custom outputs defined at an endpoint are also included as columns in this data frame. Common and useful variables include:

|**Variable**|**Description**|**Notes**|
|-|----|--------|
|**Response**  |Vector of length equal to the number of subjects, containing the generated responses for all subjects.|Not available for `Endpoint Type = Time-to-Event or Continuous with Repeated Measures`. See the Output section of [Integration Point: Response - Binary Outcome](IntegrationPointResponseBinary.html#expected-output-variable), [Integration Point: Response - Continuous Outcome](IntegrationPointResponseContinuous.html#expected-output-variable), or [Integration Point: Response - Dual Endpoints](IntegrationPointResponseDual.html#expected-output-variable) for more information.|
|**Response, Response1, ..., Response`NumVisit`**  |Vectors of length equal to the number of subjects, containing the generated responses for all subjects for each visit.|Only available for `Endpoint Type = Continuous with Repeated Measures`. See the Output section of [Integration Point: Response - Continuous Outcome with Repeated Measures](IntegrationPointResponseRepeatedMeasures.html#expected-output-variable) for more information.|
|**SurvivalTime**  |Vector of length equal to the number of subjects, containing the time to response values for all subjects for each visit.|Only available for `Endpoint Type = Time-to-Event`. See the Output section of [Integration Point: Response - Time-to-Event](IntegrationPointResponseTimeToEvent.html#expected-output-variable) for more information.|
|**ArrivalTime**|Vector of length equal to the number of subjects, containing the arrival times in the study for all subjects.|See the Output section of [Integration Point: Enrollment](IntegrationPointEnrollment.html#expected-output-variable) for more information.|
|**TreatmentID**|Vector of length equal to the number of subjects, containing the allocation indices for all subjects:<br>– `0`: Control arm.<br>– `1`: First experimental arm.<br>– etc.|See the Output section of [Integration Point: Randomization](IntegrationPointRandomization.html#expected-output-variable) for more information.|
|**CensorInd or CensorIndOrg**| Vector of length equal to the number of subjects, containing the generated censor indicator values for all subjects:<br>– `0`: Dropout.<br>– `1`: Completer.|Only available for `Endpoint Type = Continuous or Binary`. See the Output section of [Integration Point: Dropout - Continuous Outcome](IntegrationPointDropoutContinuous.html#expected-output-variable) or [Integration Point: Dropout - Binary Outcome](IntegrationPointDropoutBinary.html#expected-output-variable) for more information.|
|**DropOutTime**| Vector of length equal to the number of subjects, containing the generated dropout times for all subjects.|Only available for `Endpoint Type = Time-to-Event, Continuous with Repeated Measures or Vaccine Efficacy (Binary), or Dual`. See the Output section of [Integration Point: Dropout - Time-to-Event Outcome](IntegrationPointDropoutTimetoEvent.html#expected-output-variable), [Integration Point: Dropout - Continuous Outcome with Repeated Measures](IntegrationPointDropoutRepeatedMeasures.html#expected-output-variable),  [Integration Point: Dropout - Binary Outcome](IntegrationPointDropoutBinary.html#expected-output-variable), or  [Integration Point: Dropout - Dual Endpoints](IntegrationPointDropoutDual.html#expected-output-variable) for more information.|
|**DropoutVisitID**| Vector of length equal to the number of subjects, containing the visit ID after which each subject drops out.|Only available for `Endpoint Type = Continuous with Repeated Measures`. See the Output section of [Integration Point: Dropout - Continuous Outcome with Repeated Measures](IntegrationPointDropoutRepeatedMeasures.html#expected-output-variable) for more information.|
|**CensorInd1, CensorInd2, ..., CensorInd`NumVisit`**| Vector of length equal to the number of subjects, containing the generated censor indicator values for all subjects for each visit:<br>– `0`: Dropout.<br>– `1`: Completer.|Only available for `Endpoint Type = Continuous with Repeated Measures`. See the Output section of [Integration Point: Dropout - Continuous Outcome with Repeated Measures](IntegrationPointDropoutRepeatedMeasures.html#expected-output-variable) for more information.|

## For `Study objective = Two Arm Confirmatory - Multiple Endpoints`

For Multiple Endpoints, the variables of SimData are different.

|**Variable**|**Description**|**Notes**|
|-|----|--------|
|**SimID**|Vector of length equal to the number of subjects, indicating the simulation ID.|
|**PatId**|Vector of length equal to the number of subjects, containing the patient ID identifying a unique patient in a given simulation.|
|**ArrivalTime**|Vector of length equal to the number of subjects, containing the arrival times in the study for all subjects.|See the Output section of [Integration Point: Enrollment](IntegrationPointEnrollment.html#expected-output-variable) for more information.|
|**TreatmentID**|Vector of length equal to the number of subjects, containing the allocation indices for all subjects:<br>– `0`: Control arm.<br>– `1`: First experimental arm.<br>– etc.|See the Output section of [Integration Point: Randomization](IntegrationPointRandomization.html#expected-output-variable) for more information.|
|**TResponse.`EPNAME`**|Vector of length equal to the number of subjects, containing the generated responses for a specific endpoint.|`EPNAME` is the endpoint name specified in East Horizon. Endpoint names can also be accessed using `DesignParam$EndpointName`.|
|**CensorID.`EPNAME`**|Vector of length equal to the number of subjects, containing the generated censor indicator values for a specific endpoint:<br>– `0`: Dropout.<br>– `1`: Completer|`EPNAME` is the endpoint name specified in East Horizon. Endpoint names can also be accessed using `DesignParam$EndpointName`.|
|**Response.`EPNAME`**|Vector of length equal to the number of subjects, containing the generated responses for a specific endpoint after adjusting for endpoint and dropout rules.|`EPNAME` is the endpoint name specified in East Horizon. Endpoint names can also be accessed using `DesignParam$EndpointName`.|
|**CalRespT.`EPNAME`**|Vector of length equal to the number of subjects, containing the generated response times on calendar scale for a specific endpoint. Equivalent to `Response + ArrivalTime`.|`EPNAME` is the endpoint name specified in East Horizon. Endpoint names can also be accessed using `DesignParam$EndpointName`.|
|**DropoutID.`EPNAME`**|Vector of length equal to the number of subjects, containing whether each patient dropped out before responding for a specific endpoint:<br>– `0`: Dropout.<br>– `1`: Completer|`EPNAME` is the endpoint name specified in East Horizon. Endpoint names can also be accessed using `DesignParam$EndpointName`.|
