#' @name AnalyzeDoseFindingCont
#' @title Analyze continuous outcome for dose finding design using Fixed Sequence Pairwise t-test.
#' @param SimData Data frame with subject data generated in current simulation with one row per patient.
#'        It will have headers indicating the names of the columns. These names will be same as those used in
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime,
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of
#'        this data frame. For analysis the most relevant variables are:
#'        \describe
#'        {
#'          \item{ArrivalTime}{A numeric value with the time the patient arrived in the trial}
#'          \item{TreatmentID}{An integer value specifying the index of arms to which subjects are allocated (one arm index per subject). Index for control is 0}
#'          \item{Response}{A numeric value for the continuous endpoint response value.}
#'        }
#' @param DesignParam R List which consists of Design and Simulation Parameters which user
#'      may need to compute test statistic and perform test. User should access the variables
#'      using names for e.g., DesignParam$Alpha and not order. The items are as follows:
#'      \describe{
#'          \item{NumTreatments}{Integer. Number of Treatment arms (excluding control)}
#'          \item{Alpha}{Numeric. Type I Error (one-sided significance level)}
#'          \item{TailType}{Integer. Values are Left Tailed: 0, Right Tailed: 1}
#'          \item{VarType}{Integer. Variance Type. Values are Equal/Pooled: 4, Unequal/Welch: 5}
#'          \item{IsArmPresent}{Vector of integer flags indicating whether an arm is still present in the trial or was dropped in the interim. Length = number of treatment arms. Values are - Dropped in the interim: 0, Still present in the trial: 1}
#'          \item{MultAdjMethod}{Integer. Multiple Comparison Procedure. Values are Fixed Sequence Pairwise: 8}
#'          \item{RespLag}{Numeric. Follow up duration (optional)}
#'      }
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic
#'                 and perform test. User should access the variables using names,
#'                 for example LookInfo$NumLooks and not order. Other important variables are:
#'                 \describe{
#'                      \item{NumLooks}{An integer value with the number of looks in the study.}
#'                      \item{CurrLookIndex}{An integer value with the current index look, starting from 1.}
#'                      \item{CumCompleters}{Vector of Cumulative number of completers. Length = Number of looks.}
#'                      \item{FutBdryScale}{Integer. Futility boundary scale. Values are: Delta: 2, Isotonic Delta: 4}
#'                      \item{FutBdry}{Vector of numeric futility boundaries. Length = Number of looks. Can be NA.}
#'                      \item{PoCScale}{Integer. Proof of Concept scale. Values are High Dose vs. Control: 0}
#'                      \item{PoCThreshold}{Numeric scalar. Proof of Concept threshold value.}
#' }
#' @param OutList List or NULL. Pass-through list from previous look (for multi-look tracking).
#'        Engine sets this to NULL for the first look. Supports Numeric/Integer/Character/List.
#'        Optional.
#' @param UserParam User can pass custom scalar variables defined by users as a member of this list.
#'                  User should access the variables using names, for example UserParam$Var1 and not order.
#'                  These variables can be of the following types: Integer, Numeric, or Character.
#'                  Optional.
#' @return The function must return a list in the return statement of the function. The information below lists
#'             elements of the list, if the element is required or optional and a description of the return values if needed.
#'             \describe{
#'                  \item{Decision}{Vector of Integers or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Mandatory value. Values have the following meaning:
#'                                  \describe{
#'                                    \item{Decision = NA}{When the arm is dropped in a previous look}
#'                                    \item{Decision = 0}{when No boundary, futility or efficacy is crossed}
#'                                    \item{Decision = 1}{when the Lower Efficacy Boundary Crossed}
#'                                    \item{Decision = 2}{when the Upper Efficacy Boundary Crossed}
#'                                    \item{Decision = 3}{when the Futility Boundary Crossed}
#'                                    }
#'                                    }
#'                  \item{RawPVal}{p-Value computed from test statistics. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value.}
#'                  \item{TestStat}{Value of appropriate Test Statistic on Wald (Z) scale for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value.}
#'                  \item{Delta}{Estimate of Delta (Difference from Control) for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Conditionally Mandatory if FutBdryScale = 2 or 4.}
#'                  \item{POCStatusArm}{Per-arm Proof of Concept status. Vector of Integers (0 or 1) having length the same as number of treatment arms. 1 = PoC threshold crossed for this arm, 0 = not crossed. Optional - Dose Finding only.}
#'                  \item{POCStatus}{Overall Proof of Concept status. Integer scalar (0 or 1). 1 = PoC threshold crossed overall, 0 = not crossed. Determined by highest dose arm. Optional - Dose Finding only.}
#'                  \item{AnalysisTime}{Optional Numeric scalar. Estimate of Analysis time. Same as look time for interims. Same as study duration for the final analysis.}
#'                  \item{OutList}{List or NULL. Pass-through list to next look for multi-look tracking. Optional.}
#'                  \item{ErrorCode}{Integer. Optional value \describe{
#'                                     \item{ErrorCode = 0}{No Error}
#'                                     \item{ErrorCode > 0}{Nonfatal error, current simulation is aborted but the next simulations will run}
#'                                     \item{ErrorCode < 0}{Fatal error, no further simulation will be attempted}
#'                                     }
#'                                     }
#'                      }
#' @details
#' This function implements Fixed Sequence Pairwise testing for dose-finding studies with continuous endpoints.
#' The Fixed Sequence gatekeeping procedure tests hypotheses sequentially from the highest dose downward,
#' rejecting the null hypothesis only if the raw p-value is less than the total alpha. Once a hypothesis fails
#' to reject, all lower dose hypotheses are automatically rejected (futility cascade).
#' @export
AnalyzeDoseFindingCont <- function(SimData, DesignParam,
                                  LookInfo,
                                  OutList = NULL,
                                  UserParam = NULL)
{
  ErrorCode <- 0L

  # ========================================================================
  # Step 1: Extract parameters from DesignParam
  # ========================================================================
  NumTrt       <- DesignParam$NumTreatments
  TotalAlpha   <- DesignParam$Alpha
  TailType     <- DesignParam$TailType
  VarType      <- DesignParam$VarType
  IsArmPresent <- DesignParam$IsArmPresent

  # ========================================================================
  # Step 2: Extract parameters from LookInfo
  # ========================================================================
  NumLooks      <- LookInfo$NumLooks
  CurrLookIndex <- LookInfo$CurrLookIndex
  FutBdryScale  <- LookInfo$FutBdryScale
  FutBdry       <- LookInfo$FutBdry

  PoCScale     <- LookInfo$PoCScale
  PoCThreshold <- LookInfo$PoCThreshold

  # ========================================================================
  # Step 3: Initialize output vectors
  # ========================================================================
  # Decision vector: NA = dropped, 0 = no boundary, 1 = lower eff, 2 = upper eff, 3 = futility
  DecisionVec <- rep(0L, NumTrt)

  # Raw p-values from pairwise t-tests
  RawPValVec <- rep(NA_real_, NumTrt)

  # Test statistics (t-values on Wald/Z scale)
  TestStatVec <- rep(NA_real_, NumTrt)

  # Delta estimates (mean_treatment - mean_control)
  DeltaVec <- rep(NA_real_, NumTrt)

  # PoC status vectors
  POCStatusArmVec <- rep(0.0, NumTrt)
  OverallPOC      <- 0.0

  # ========================================================================
  # Step 4: Compute Analysis Time
  # ========================================================================
  RespLag <- ifelse(!is.null(DesignParam$RespLag), DesignParam$RespLag, 0)
  CompletionTimes <- sort(SimData$ArrivalTime + RespLag)
  TargetCompleters <- LookInfo$CumCompleters[CurrLookIndex]

  if (!is.null(TargetCompleters) &&
      !is.na(TargetCompleters) &&
      TargetCompleters <= length(CompletionTimes)) {
    EstAnalysisTime <- CompletionTimes[TargetCompleters]
  } else {
    EstAnalysisTime <- max(CompletionTimes, na.rm = TRUE)
  }

  tryCatch({

    # ====================================================================
    # Step 5: Identify active and dropped arms
    # ====================================================================
    SelectedArmIndex <- which(IsArmPresent == 1)

    if (length(SelectedArmIndex) == 0) {
      ErrorCode <- 1L
      return(list(
        Decision     = as.integer(DecisionVec),
        RawPVal      = as.double(RawPValVec),
        TestStat     = as.double(TestStatVec),
        Delta        = as.double(DeltaVec),
        POCStatusArm = as.integer(POCStatusArmVec),
        POCStatus    = as.integer(OverallPOC),
        AnalysisTime = as.double(EstAnalysisTime),
        OutList      = OutList,
        ErrorCode    = as.integer(ErrorCode)
      ))
    }

    # Mark dropped arms as NA in Decision
    DroppedArms <- which(IsArmPresent == 0)
    if (length(DroppedArms) > 0) {
      DecisionVec[DroppedArms] <- NA_integer_
    }

    # ====================================================================
    # Step 6: Extract control data
    # ====================================================================
    CtrlResp <- SimData$Response[SimData$TreatmentID == 0]
    nC    <- length(CtrlResp)
    meanC <- mean(CtrlResp)
    varC  <- var(CtrlResp)

    # ====================================================================
    # Step 7: Fixed Sequence Pairwise Testing (Top-Down from Highest Dose)
    # ====================================================================
    NumActive   <- length(SelectedArmIndex)
    CurrentArms <- SelectedArmIndex

    while (NumActive > 0) {

      # Highest dose arm under test
      TrtArmIndex <- CurrentArms[NumActive]

      # Compute pairwise results for all currently active arms
      pairwise_results <- list(
        RawPval  = numeric(NumActive),
        TestStat = numeric(NumActive),
        Delta    = numeric(NumActive)
      )

      for (j in seq_along(CurrentArms)) {
        k <- CurrentArms[j]
        TrtResp <- SimData$Response[SimData$TreatmentID == k]
        nT    <- length(TrtResp)
        meanT <- mean(TrtResp)
        varT  <- var(TrtResp)

        DeltaEst    <- meanT - meanC
        pairwise_results$Delta[j] <- DeltaEst

        # Compute variance and degrees of freedom
        if (VarType == 4L) {
          # Equal variance: pooled
          Sp2 <- ((nC - 1) * varC + (nT - 1) * varT) / (nC + nT - 2)
          SE  <- sqrt(Sp2 * (1/nC + 1/nT))
          dof <- nC + nT - 2
        } else {
          # Unequal variance: Welch
          vC  <- varC / nC
          vT  <- varT / nT
          SE  <- sqrt(vC + vT)
          dof <- round((vC + vT)^2 / (vC^2/(nC - 1) + vT^2/(nT - 1)))
        }

        # Compute test statistic and p-value
        if (SE < 1e-12) {
          pairwise_results$TestStat[j] <- 0.0
          pairwise_results$RawPval[j]  <- 1.0
        } else {
          tstat <- DeltaEst / SE
          pairwise_results$TestStat[j] <- tstat

          if (TailType == 1L) {
            # Right-Tail: P(T > tstat)
            pairwise_results$RawPval[j] <- pt(tstat, df = dof, lower.tail = FALSE)
          } else {
            # Left-Tail: P(T < tstat)
            pairwise_results$RawPval[j] <- pt(tstat, df = dof, lower.tail = TRUE)
          }
        }
      }

      # Store results for highest arm
      HighIdx <- NumActive
      DeltaVec[TrtArmIndex]    <- pairwise_results$Delta[HighIdx]
      RawPValVec[TrtArmIndex]  <- pairwise_results$RawPval[HighIdx]
      TestStatVec[TrtArmIndex] <- pairwise_results$TestStat[HighIdx]

      # ===================================================================
      # Step 8: Fixed Sequence Decision Logic
      # ===================================================================
      if (pairwise_results$RawPval[HighIdx] < TotalAlpha) {
        # ---- EFFICACY: Reject null hypothesis for highest arm ----
        DecisionVec[TrtArmIndex] <- ifelse(TailType == 1L, 2L, 1L)

        # Remove this arm and continue with lower doses
        CurrentArms <- CurrentArms[CurrentArms != TrtArmIndex]
        NumActive   <- length(CurrentArms)

      } else {
        # ---- NO EFFICACY: Cascade futility ----

        # Store results for remaining arms
        for (jj in seq_along(CurrentArms)) {
          arm <- CurrentArms[jj]
          if (is.na(DeltaVec[arm]))    DeltaVec[arm]    <- pairwise_results$Delta[jj]
          if (is.na(RawPValVec[arm]))  RawPValVec[arm]  <- pairwise_results$RawPval[jj]
          if (is.na(TestStatVec[arm])) TestStatVec[arm] <- pairwise_results$TestStat[jj]
        }

        # ---- Check Futility Boundary (if applicable) ----
        HasFutility <- !is.null(FutBdry) && !all(is.na(FutBdry))

        if (HasFutility && !is.na(FutBdry[CurrLookIndex])) {
          FutBdryVal <- FutBdry[CurrLookIndex]

          for (jj in seq_along(CurrentArms)) {
            arm <- CurrentArms[jj]
            futility_hit <- FALSE

            if (FutBdryScale %in% c(2L, 4L)) {
              # Delta Scale: compare delta estimate against futility boundary
              if (TailType == 1L) {
                futility_hit <- (DeltaVec[arm] < FutBdryVal)
              } else {
                futility_hit <- (DeltaVec[arm] > FutBdryVal)
              }
            } else {
              # Z Scale: compare test statistic against futility boundary
              ts <- pairwise_results$TestStat[jj]
              if (TailType == 1L) {
                futility_hit <- (ts < FutBdryVal)
              } else {
                futility_hit <- (ts > FutBdryVal)
              }
            }

            if (futility_hit && DecisionVec[arm] == 0L) {
              DecisionVec[arm] <- 3L  # Futility
            }
          }
        }

        # At final look: assign futility to all remaining arms without decision
        if (CurrLookIndex == NumLooks) {
          lowerArmIdx <- CurrentArms[CurrentArms <= TrtArmIndex]
          remaining   <- lowerArmIdx[DecisionVec[lowerArmIdx] == 0L]
          if (length(remaining) > 0) {
            DecisionVec[remaining] <- 3L
          }
        }

        break  # Exit the while loop (Fixed Sequence stops here)
      }
    }

    # ====================================================================
    # Step 9: Proof of Concept Assessment
    # ====================================================================
    if (!is.null(PoCThreshold) && !is.na(PoCThreshold)) {
      # Get isotonic means using PAVA for PoC computation
      ActiveForPoC <- which(!is.na(DeltaVec))

      if (length(ActiveForPoC) > 0) {
        # Simple isotonic regression: enforce monotonicity on deltas
        iso_deltas <- pava_isotonic(DeltaVec[ActiveForPoC], TailType)

        # PoC: independent per-arm check for Pairwise test
        if (TailType == 1L) {
          # Right-Tail: PoC if delta > threshold
          poc_arms <- which(round(iso_deltas, 7) > PoCThreshold)
        } else {
          # Left-Tail: PoC if delta < threshold
          poc_arms <- which(round(iso_deltas, 7) < PoCThreshold)
        }

        if (length(poc_arms) > 0) {
          POCStatusArmVec[ActiveForPoC[poc_arms]] <- 1L
        }

        # Overall PoC: determined by highest dose arm
        HighestActiveArm <- max(ActiveForPoC)
        POCStatusArmVec[HighestActiveArm] <- ifelse(
          (TailType == 1L && iso_deltas[length(iso_deltas)] > PoCThreshold) ||
          (TailType == 0L && iso_deltas[length(iso_deltas)] < PoCThreshold),
          1L, 0L
        )
        OverallPOC <- POCStatusArmVec[HighestActiveArm]
      }
    }

  }, error = function(e) {
    ErrorCode <<- -1L
  })

  # ========================================================================
  # Step 10: Prepare OutList for next look
  # ========================================================================
  NewOutList <- list(
    PrevDecisions = DecisionVec,
    PrevDeltas    = DeltaVec,
    LookIndex     = CurrLookIndex
  )

  # ========================================================================
  # Step 11: Return Results
  # ========================================================================
  return(list(
    Decision     = as.integer(DecisionVec),
    RawPVal      = as.double(RawPValVec),
    TestStat     = as.double(TestStatVec),
    Delta        = as.double(DeltaVec),
    POCStatusArm = as.integer(POCStatusArmVec),
    POCStatus    = as.integer(OverallPOC),
    AnalysisTime = as.double(EstAnalysisTime),
    OutList      = NewOutList,
    ErrorCode    = as.integer(ErrorCode)
  ))
}


# ==============================================================================
# HELPER FUNCTION: Isotonic Regression via PAVA
# ==============================================================================
#' @keywords internal
#' @description
#' Computes isotonic regression to enforce monotonicity on values using
#' the Pool Adjacent Violators Algorithm (PAVA).
#'
#' @param values numeric vector of values to be monotonized
#' @param tail_type integer — 0 = non-increasing, 1 = non-decreasing
#'
#' @return numeric vector of isotonic values (same length as input)
#'
#' @details
#' The PAVA algorithm iteratively pools adjacent blocks that violate the
#' monotonicity constraint, replacing each block with its weighted average.
#' Used for PoC assessment in dose-finding studies.
pava_isotonic <- function(values, tail_type)
{
  n <- length(values)
  if (n == 0) return(numeric(0))

  # For non-increasing (left-tail), negate values
  if (tail_type == 0L) values <- -values

  block_val <- values
  block_idx <- as.list(1:n)

  repeat {
    merged <- FALSE
    i <- 1
    while (i < length(block_val)) {
      if (block_val[i] > block_val[i + 1]) {
        # Merge blocks i and i+1 with simple average
        new_val <- mean(c(block_val[i], block_val[i + 1]))
        block_val[i] <- new_val
        block_val <- block_val[-(i + 1)]
        block_idx[[i]] <- c(block_idx[[i]], block_idx[[i + 1]])
        block_idx <- block_idx[-(i + 1)]
        merged <- TRUE
      } else {
        i <- i + 1
      }
    }
    if (!merged) break
  }

  # Reconstruct result vector
  result <- numeric(n)
  for (j in seq_along(block_val)) {
    result[block_idx[[j]]] <- block_val[j]
  }

  # Negate back if left-tail
  if (tail_type == 0L) result <- -result

  return(result)
}