######################################################################################################################## .
#' AnalyzeUsingEastLogrankFormula
#' @name AnalyzeUsingEastLogrankFormula
#' @title Compute the statistic using formulas Q.242 and Q.243 in the East manual.
#' @author Anoop Singh Rawat, Shubham Lahoti, and Gabriel Potvin
#' @description Use the formulas Q.242 and Q.243 in the East manual to compute the statistic.  The purpose of this example is to demonstrate how the analysis and decision making can be modified in a simple approach.
#'              The test statistic is compared to the lower boundary computed and sent by East Horizon as an input. This example does NOT include a futility rule.
#' @param SimData Data frame with subject data generated in current simulation with one row per patient.
#'        It will have headers indicating the names of the columns. These names will be same as those used in
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime,
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of
#'        this data frame. For analysis the most relevant variables are:
#'          SimData$ArrivalTime A numeric value with the time the patient arrived in the trial
#'          SimData$TreatmentID An integer value where 0 indicates control treatment and 1 experimental treatment.
#'          SimData$SurvivalTime Numeric value for the survival time or time-to-event for the patient, note this is not the time in the trial
#'                               that the patient experiences the event.
#' @param DesignParam Input Parameters which user may need to compute test statistic and perform test.
#'                    User should access the variables using names, for example,  DesignParam$Alpha, and not order.
#'                    For details of this list please see below.
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic
#'                 and perform test. User should access the variables using names,
#'                 for example LookInfo$NumLooks and not order. Other important variables in group sequential designs are:
#'                   LookInfo$NumLooks An integer value with the number of looks in the study
#'                   LookInfo$CurrLookIndex An integer value with the current index look, starting from 1
#'                   LookInfo$InfoFrac A numeric vector containing information fraction
#' @param UserParam A list of user defined parameters in East Horizon. You must have a default = NULL, as in this example. If UserParam values are supplied in East Horizon, they will be elements of the list, e.g., UserParam$ParameterName.
#'                  User should access the variables using names, for example UserParam$Var1 and not order.
#'                  These variables can be of the following types: Integer, Numeric, or Character
#' @return A named list containing log-rank `TestStat`, integer `Decision`, integer `ErrorCode`, and observed `HazardRatio`.
#' @details
#' ## CyneRgy Decision Helpers
#'
#' The analysis may use `CyneRgy::GetDecisionString()` and
#' `CyneRgy::GetDecision()` to determine the decision returned to
#' East Horizon Explore.
#'
#' When these helpers are used, the following input fields are required
#' and MUST be included when generating sample/test data:
#'
#' DesignParam:
#'   - TailType: Integer indicating the direction of the statistical test.
#'       0 = Left-tailed
#'       1 = Right-tailed
#'
#' LookInfo (for group sequential designs, NULL for fixed designs):
#' When not NULL, must contain the following fields:
#'   - NumLooks: Total number of looks.
#'   - CurrLookIndex: Current look index, starting at 1.
#'   - RejType: Integer identifying which stopping boundaries are enabled.
#'       0 = 1-Sided Efficacy Upper
#'       1 = 1-Sided Futility Upper
#'       2 = 1-Sided Efficacy Lower
#'       3 = 1-Sided Futility Lower
#'       4 = 1-Sided Efficacy Upper and Futility Lower
#'       5 = 1-Sided Efficacy Lower and Futility Upper
#'       6 = 2-Sided Efficacy Only (not used in East Horizon Explore)
#'       7 = 2-Sided Futility Only (not used in East Horizon Explore)
#'       8 = 2-Sided Efficacy and Futility (not used in East Horizon Explore)
#'       9 = Equivalence (not used in East Horizon Explore)
#'
######################################################################################################################## .

AnalyzeUsingEastLogrankFormula <- function( SimData, DesignParam, LookInfo = NULL, UserParam = NULL )
{
    # Step 1: Retrieve necessary information from the objects East Horizon sent. You may not need all the variables ####
    if( !is.null( LookInfo ) )
    {
        # Look info was provided so use it
        nQtyOfLooks          <- LookInfo$NumLooks
        nLookIndex           <- LookInfo$CurrLookIndex
        vCumEvents           <- LookInfo$InfoFrac * DesignParam$MaxEvents
        nQtyOfEvents         <- vCumEvents[ nLookIndex ]
        dEffBdry             <- LookInfo$EffBdryLower[ nLookIndex ]
        nRejType             <- LookInfo$RejType
        nTailType            <- DesignParam$TailType
    }
    else
    {   # Look info is not provided for fixed sample designs so fetch the information appropriately
        nQtyOfLooks          <- 1
        nLookIndex           <- 1
        nQtyOfEvents         <- DesignParam$MaxEvents
        dEffBdry             <- DesignParam$CriticalPoint
        nTailType            <- DesignParam$TailType
    }

    SimData$TimeOfEvent      <- SimData$ArrivalTime + SimData$SurvivalTime    # This is the calendar time in the trial that the patients event is observed

    # Compute the time of analysis
    SimData                  <- SimData[ order( SimData$TimeOfEvent ), ]
    dTimeOfAnalysis          <- SimData[ nQtyOfEvents, ]$TimeOfEvent

    # Add the Observed Time variable
    SimData                  <- SimData[ SimData$ArrivalTime <= dTimeOfAnalysis , ]   # Exclude any patients that were not enrolled by the time of the analysis
    SimData$Event            <- ifelse( SimData$TimeOfEvent > dTimeOfAnalysis, 0, 1 )  # If the event is observed after the analysis it is not observed, eg censored
    SimData$ObservedTime     <- ifelse( SimData$TimeOfEvent > dTimeOfAnalysis, dTimeOfAnalysis - SimData$ArrivalTime, SimData$TimeOfEvent - SimData$ArrivalTime )

    # Order the data by observed time for the remainder of the computations
    SimData                  <- SimData[ order( SimData$ObservedTime ), ]

    # Compute Observed HR

    coxModel                 <- survival::coxph( survival::Surv( ObservedTime, Event ) ~ TreatmentID, data = SimData )
    dTrueHR                  <- exp( coxModel$coefficients )

    SimData$EventOnTreatment <- ifelse( SimData$TreatmentID == 1, SimData$Event, 0 ) # If the event is observed on treatment
    SimData$EventOnControl   <- ifelse( SimData$TreatmentID == 0, SimData$Event, 0 ) # If the event is observed on control

    # Arm wise count of subjects at risk at the beginning. Is same as arm wise sample size
    nSubjectsAtRiskTreatment <- nrow( SimData[ SimData$TreatmentID == 1, ] )
    nSubjectsAtRiskControl   <- nrow( SimData[ SimData$TreatmentID == 0, ] )

    # Initialize intermediate quantities required for test statistic computation
    dNum <- 0
    dDen <- 0

    # Iterate over subjects to calculate dNum and dDen required for test statistic computation
    for( nSubject in 1:nrow( SimData ) )
    {   # Update the count of subjects at risk for each arm for non event times
        if( SimData$Event[ nSubject ] == 0 )
        {
            if( SimData$TreatmentID[ nSubject ] == 1 )
            {
                nSubjectsAtRiskTreatment <- nSubjectsAtRiskTreatment - 1
            }
            if( SimData$TreatmentID[ nSubject ] == 0 )
            {
                nSubjectsAtRiskControl   <- nSubjectsAtRiskControl - 1
            }

        } # For subjects with events, compute dNum and dDen
        if( SimData$Event[ nSubject ] == 1 )
        {
            nEventsOnTreatment           <- SimData$EventOnTreatment[ nSubject ]
            nEventsOnControl             <- SimData$EventOnControl[ nSubject ]
            nEvents                      <- nEventsOnTreatment + nEventsOnControl
            nSubjectsAtRisk              <- nSubjectsAtRiskTreatment + nSubjectsAtRiskControl
            # Equation Q.242 in East Manual
            dNum <- dNum + nEventsOnTreatment - nSubjectsAtRiskTreatment * nEvents / nSubjectsAtRisk
            # Generate dDen based on number of subjects at risk
            if( nSubjectsAtRisk != 1 )
            {   # Equation Q.243 in East Manual
                dDen <- dDen + nSubjectsAtRiskTreatment * nSubjectsAtRiskControl * ( nSubjectsAtRisk - nEvents ) * nEvents / ( ( nSubjectsAtRisk - 1 ) * nSubjectsAtRisk ^ 2 )
            }
            # Update the count of subjects at risk before the next iteration
            nSubjectsAtRiskTreatment     <- nSubjectsAtRiskTreatment - nEventsOnTreatment
            nSubjectsAtRiskControl       <- nSubjectsAtRiskControl - nEventsOnControl
        }
    }

    # Compute the logrank test statistic
    dTS       <- dNum / sqrt( dDen )

    # Generate decision using GetDecisionString and GetDecision helpers
    strDecision <- CyneRgy::GetDecisionString( LookInfo, nLookIndex, nQtyOfLooks,
                                               bIAEfficacyCondition = dTS <  dEffBdry,
                                               bFAEfficacyCondition = dTS <  dEffBdry )
    nDecision <- CyneRgy::GetDecision( strDecision, DesignParam, LookInfo )

    nError   <- 0

    lRet      <- list( TestStat = as.double( dTS ),
                      Decision  = as.integer( nDecision ),
                      ErrorCode = as.integer( nError ),
                      HazardRatio = as.double( dTrueHR ) )
    return( lRet )
}
