########################################################################################################################
#  Last Modified Date: {{CREATION_DATE}}
#  
#' @name {{FUNCTION_NAME}}
#' 
#' @title Template for analysis task in R when the outcome is Dual Endpoints. 
#'
#' @param SimData Data frame with subject data generated in current simulation with one row per patient.
#'        It will have headers indicating the names of the columns. These names will be same as those used in
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime,
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of
#'        this data frame. For analysis the most relevant variables are:
#'          SimData$ArrivalTime :   A numeric value with the time the patient arrived in the trial
#'          SimData$TreatmentID :   An integer value where 0 indicates control treatment and 1 experimental treatment.
#'          SimData$ResponseX   :   Numeric value for the survival time or time-to-event for the patient on Endpoint X
#' @param DesignParam Input Parameters which user may need to compute test statistic and perform test.
#'                    User should access the variables using names, for example, DesignParam$Alpha, and not order.
#'                    For details of this list please see below.
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic
#'                 and perform test. User should access the variables using names,
#'                 for example LookInfo$NumLooks and not order. Other important variables in group sequential designs are:
#'                   LookInfo$NumLooks      :   An integer value with the number of looks in the study
#'                   LookInfo$CurrLookIndex :   An integer value with the current index look, starting from 1
#'                   LookInfo$InfoFrac      :   A numeric vector containing information fraction
#' @param UserParam User can pass custom scalar variables defined by users as a member of this list.
#'                  User should access the variables using names, for example UserParam$Var1 and not order.
#'                  These variables can be of the following types: Integer, Numeric, or Character
#' @return The function must return a list in the return statement of the function. The information below lists
#'             elements of the list, if the element is required or optional and a description of the return values if needed.
#'             \describe{
#'                  \item{TestStat}{Required value. Test statistic on Z-scale.}
#'                  \item{ErrorCode}{Optional integer value \describe{
#'                                     \item{ErrorCode = 0}{No Error}
#'                                     \item{ErrorCode > 0}{Non fatal error, current simulation is aborted but the next simulations will run}
#'                                     \item{ErrorCode < 0}{Fatal error, no further simulation will be attempted}
#'                                     }}
#'                  \item{HR}{Required numeric value - Hazard Ratio,
#'                            Only applicable for time-to-event data.}
#'             }
#'
#' @description
#' This template can be used as a starting point for developing custom functionality.  The function signature must remain the same.  
#' If you are creating task that requires use of additional parameters that listed above, add that as element to to UserParam.
{{FUNCTION_NAME}} <- function(SimData, DesignParam, LookInfo = NULL, UserParam = NULL) 
{
    require(survival)
    
    dTrueHR     <- 0
    dTS         <- 0
    ErrorCode   <- 0
    
    # Finding the endpoint ID and name of the endpoint to be analysed.
    EPID    <- ifelse(is.nan(DesignParam$TestStat$`Endpoint 1`), 1, 2)
    EPName  <- DesignParam$EndpointName[EPID] 

    bGSD <- ifelse(is.null(LookInfo), FALSE, TRUE)                              # Is the trial using Group sequential Design?
    syncEPID <- ifelse(bGSD, LookInfo$SyncInterim, DesignParam$PlanEndTrial)    # Endpoint ID to be used for look positioning
    syncEPType <- DesignParam$EndpointType[[syncEPID]]                          # Endpoint type of the endpoint used for look positioning
    
    if(bGSD)               # Group Sequential Design   
    {
        # Write logic to read GS Design inputs
    } 
    else                    # Fixed Sample Design
    {
        # Write logic to read FSD Design inputs
    }
    
    # Compute Hazard Ratio and test statistic taking into account the analysis time.

    
    
    return(list(
        TestStat  = as.double(dTS),
        HR        = as.double(dTrueHR),
        ErrorCode = as.integer(Error)
    ))
}