#  Last Modified Date: {{CREATION_DATE}}
#' @name {{FUNCTION_NAME}}
#' @param SimData Data frame with subject data generated in current simulation with one row per patient. 
#'        It will have headers indicating the names of the columns. These names will be same as those used in 
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime, 
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of 
#'        this data frame. For analysis the most relevant variables are:
#'        \describe
#'        {
#'          \item{ArrivalTime}{ A numeric value with the time the patient arrived in the trial}
#'          \item{TreatmentID}{An integer value where 0 indicates control treatment and 1 experimental treatment.}
#'          \item{SurvivalTime}{Numeric value for the survival time or time-to-event for the patient, note this is not the time in the trial
#'                               that the patient experiences the event.}
#'          \item{DropOutTime}{Numeric value for the dropout time for the patient in a time to event trial.}
#'        }
#' @param DesignParam R List which consists of Design and Simulation Parameters which user
#'      may need to compute test statistic and perform test. User should access the variables
#'      using names for e.g., DesignParam$Alphae and not order.  Them items are as follows:
#'      \describe{
#'          \item{SampleSize}{Sample size of the trial}
#'          \item{Alpha}{Type I Error}
#'          \item{TestType}{Values are One side: 0; Two Sided: 1, Two Sided, Asymmetric: 2}
#'          \item{TailType}{Values are Left Tailed: 0, Right Tailed: 1}
#'          \item{LowerAlpha}{Two Sided Asymmetric Tests}
#'          \item{UpperAlpha}{Two Sided Asymmetric Tests}
#'          \item{MaxEvents}{Maximum Events in a time to event based trial}
#'          \item{FollowUpType}{For survival tests, Follow Up Type. Possible values are: Until End ofS Study: 0, For fixed period: 1}
#'      
#'      }
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic 
#'                 and perform test. User should access the variables using names, 
#'                 for example LookInfo$NumLooks and not order. Other important variables in group sequential designs are: 
#'                 \describe{
#'                      \item{NumLooks}{An integer value with the number of looks in the study}
#'                      \item{CurrLookIndex}{An integer value with the current index look, starting from 1}
#'                      \item{InfoFrac}{Information fraction}
#'                      \item{CumAlpha}{cumulative alpha spent, one sided tests}
#'                      \item{EffBdryScale}{Efficacy boundary scale. Possible vaues are: Z Scale: 0, p-Value Scale: 1}
#'                      \item{EffBdry}{Vector of efficacy bondaries, one sided tests}
#'                      \item{EffBdryUpper}{Vector of upper efficacy bondaries, two sided tests}
#'                      \item{EffBdryLower}{Vector of lower efficacy boundary, two sided tests}
#'                      \item{FutBdryScale}{Futility boundary scale. Possible value are:  Z Scale: 0, p-Value Scale: 1, Delta Scale: 2, Conditional Power Scale: 3}
#'                      \item{FutBdry}{Vector of futility bondaries, one sided tests.}
#'                      \item{FutBdryUpper}{Vector of upper futility boundaries, two sided tests}
#'                      \item{FutBdryLower}{Vector of lower futility boundaries, two sided tests}
#'                 }
#' @param UserParam User can pass custom scalar variables defined by users as a member of this list. 
#'                  User should access the variables using names, for example UserParam$Var1 and not order. 
#'                  These variables can be of the following types: Integer, Numeric, or Character
#' @return The function must return a list in the return statement of the function. The information below lists 
#'             elements of the list, if the element is required or optional and a description of the return values if needed.
#'             \describe{
#'                  \item{Decision}{Optional value. Integer Value with the following meaning:
#'                                  \describe{
#'                                    \item{Decision = 0}{when No boundary, futility or efficacy is  crossed}
#'                                    \item{Decision = 1}{when the Lower Efficacy Boundary Crossed}
#'                                    \item{Decision = 2}{when the Upper Efficacy Boundary Crossed}
#'                                    \item{Decision = 3}{when the Futility Boundary Crossed}
#'                                    \item{Decision = 4}{when the Equivalence Boundary Crossed}
#'                                    } 
#'                                    }
#'                  \item{TestStat}{Numeric value. Required if Decision is not returned}
#'                  \item{ErrorCode}{Optional integer value \describe{ 
#'                                     \item{ErrorCode = 0}{No Error}
#'                                     \item{ErrorCode > 0}{Nonfatal error, current simulation is aborted but the next simulations will run}
#'                                     \item{ErrorCode < 0}{Fatal error, no further simulation will be attempted}
#'                                     }
#'                                     }
#'                  \item{Delta}{HazardRatio}{Optional numeric value. 
#'                                            Used in East Horizon Explore for creating the observed hazard ratio graph. 
#'                                            Only applicable for time-to-event data.}
#'                      }
{{FUNCTION_NAME}} <- function( SimData, DesignParam, LookInfo = NULL, UserParam = NULL )
{
    library(CyneRgy)
    
    nError 	         <- 0
    nDecision 	     <- 0
    dTestStatistic   <- 0
    bIAEfficayCheck  <- TRUE
    bIAFutilityCheck <- FALSE
    bFAEfficacyCheck <- TRUE
    
    # Step 1 - If LookInfo is Null, then this is a fixed design and we use the DesignParam$MaxEvents
    if( !is.null( LookInfo ) )
    {
        # Look info was provided so this is a group sequential design and need to use the look information
        nQtyOfLooks  <- LookInfo$NumLooks
        nLookIndex   <- LookInfo$CurrLookIndex
        CumEvents    <- LookInfo$InfoFrac*DesignParam$MaxEvents
        nQtyOfEvents <- CumEvents[ nLookIndex ]
    }
    else
    {
        nQtyOfLooks  <- 1
        nLookIndex   <- 1
        nQtyOfEvents <- DesignParam$MaxEvents 
    }
    
    
    # Step 2 - The data that is sent in SimData is the simulated data, and the first step ####
    #           is to create an analysis data set based on the number events to get the time 
    
    # Create the calendar time in the trial that the patients' event are observed
    SimData$TimeOfEvent  <- SimData$ArrivalTime + SimData$SurvivalTime    
    
    # Compute the time of analysis using the number of events 
    SimData              <- SimData[ order( SimData$TimeOfEvent), ]
    dTimeOfAnalysis      <- SimData[ nQtyOfEvents, ]$TimeOfEvent
    
    # Add the Observed Time variable 
    SimData              <- SimData[ SimData$ArrivalTime <= dTimeOfAnalysis ,]   # Exclude any patients that were not enrolled by the time of the analysis
    SimData$Event        <- ifelse( SimData$TimeOfEvent > dTimeOfAnalysis, 0, 1 )  # If the event is observed after the analysis it is not observed, e.g., censored 
    SimData$ObservedTime <- ifelse( SimData$TimeOfEvent > dTimeOfAnalysis, dTimeOfAnalysis - SimData$ArrivalTime, SimData$TimeOfEvent - SimData$ArrivalTime )
    
    # Step 3 - Perform the desired analysis ####
    # Example - Fit a cox model 
    # fitCox    <- coxph( Surv( ObservedTime, Event ) ~ as.factor( TreatmentID ), data = SimData )
    
    # Step 4 - Use the analysis to make a decision ####
    # The example code below uses the Cox model to compute the p-value and if less than alpha return efficacy value
    # dPValue   <- summary(fitCox)$coefficients[,"Pr(>|z|)"]
    # dZVal     <- summary(fitCox)$coefficients[,"z"]
    # dPValue   <- pnorm( dZVal, lower.tail = TRUE)
    
    # Step 5 - Setup look decision logic
    # Generate decision using GetDecisionString and GetDecision helpers
    strDecision <- CyneRgy::GetDecisionString( LookInfo, nLookIndex, nQtyOfLooks, 
                                               bIAEfficacyCondition = dPValue <= DesignParam$Alpha,
                                               bIAFutilityCondition = bIAFutilityCheck,
                                               bFAEfficacyCondition = dPValue <= DesignParam$Alpha)
    nDecision <- CyneRgy::GetDecision( strDecision, DesignParam, LookInfo )
    
    lRet <- list(TestStat = as.double(dTestStatistic),
                 Decision  = as.integer(nDecision), 
                 ErrorCode = as.integer(nError))
    return( lRet )
}

