######################################################################################################################## .
# Last Modified Date: {{CREATION_DATE}}
#' @name {{FUNCTION_NAME}}
#' @title Analyze Continuous Dose-Finding Outcomes
#' @description Analyze simulated continuous outcomes for a dose-finding design at the current look.
#' @param SimData Data frame with subject data generated in current simulation with one row per patient.
#'        It will have headers indicating the names of the columns. These names will be same as those used in
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime,
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of
#'        this data frame. For analysis the most relevant variables are:
#'        \describe{
#'          \item{ArrivalTime}{A numeric value with the time the patient arrived in the trial}
#'          \item{TreatmentID}{An integer value specifying the index of arms to which subjects are allocated (one arm index per subject). Index for control is 0}
#'          \item{Response}{A numeric value for the continuous endpoint response value.}
#'          \item{CensorInd}{An integer value indicating whether the subject was censored or not.}
#'        }
#' @param DesignParam R List which consists of Design and Simulation Parameters which user
#'      may need to compute test statistic and perform test. User should access the variables
#'      using names for e.g., DesignParam$Alpha and not order. The items are as follows:
#'      \describe{
#'          \item{NumTreatments}{Integer. Number of Treatment arms (excluding control)}
#'          \item{Alpha}{Numeric. Type I Error (one-sided significance level)}
#'          \item{TailType}{Integer. Values are Left Tailed: 0, Right Tailed: 1}
#'          \item{VarType}{Integer. Variance Type. Values are Equal/Pooled: 4, Unequal/Welch: 5}
#'          \item{IsArmPresent}{Vector of integer flags indicating whether an arm is still present in the trial or was dropped in the interim. Length = number of treatment arms. Values are - Dropped in the interim: 0, Still present in the trial: 1}
#'          \item{MultAdjMethod}{Integer. Multiple Comparison Procedure. Values are Fixed Sequence Pairwise: 8}
#'          \item{RespLag}{Numeric. Follow up duration (optional)}
#'          \item{MaxCompleters}{Integer. Maximum Number of Completers.}
#'      }
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic
#'                 and perform test. User should access the variables using names,
#'                 for example LookInfo$NumLooks and not order. Other important variables are:
#'                 \describe{
#'                      \item{NumLooks}{An integer value with the number of looks in the study.}
#'                      \item{CurrLookIndex}{An integer value with the current index look, starting from 1.}
#'                      \item{CumCompleters}{Vector of Cumulative number of completers. Length = Number of looks.}
#'                      \item{FutBdryScale}{Integer. Futility boundary scale. Values are: Delta: 2, Isotonic Delta: 4, Z Scale: 0}
#'                      \item{FutBdry}{Vector of numeric futility boundaries. Length = Number of looks. Can be NA.}
#'                      \item{PoCScale}{Integer. Proof of Concept scale. Values are High Dose vs. Control: 0}
#'                      \item{PoCThreshold}{Numeric scalar. Proof of Concept threshold value.}
#' }
#' @param OutList List or NULL. Pass-through list from previous look (for multi-look tracking).
#'        Engine sets this to NULL for the first look. Supports Numeric/Integer/Character/List.
#'        Optional.
#' @param UserParam User can pass custom scalar variables defined by users as a member of this list.
#'                  User should access the variables using names, for example UserParam$Var1 and not order.
#'                  These variables can be of the following types: Integer, Numeric, or Character.
#'                  Optional.
#' @return The function must return a list in the return statement of the function. The information below lists
#'             elements of the list, if the element is required or optional and a description of the return values if needed.
#'             \describe{
#'                  \item{Decision}{Vector of Integers or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. All other outputs become optional if Decision is returned. Values have the following meaning:
#'                                  \describe{
#'                                    \item{Decision = NA}{When the arm is dropped in a previous look}
#'                                    \item{Decision = 0}{when No boundary, futility or efficacy is crossed}
#'                                    \item{Decision = 1}{when the Lower Efficacy Boundary Crossed}
#'                                    \item{Decision = 2}{when the Upper Efficacy Boundary Crossed}
#'                                    \item{Decision = 3}{when the Futility Boundary Crossed}
#'                                    }
#'                                    }
#'                  \item{RawPVal}{p-Value computed from test statistics. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. All other outputs become optional if RawPVal is returned and if there is no Futility Boundary.}
#'                  \item{TestStat}{Value of appropriate Test Statistic on Wald (Z) scale for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. All other outputs become optional if TestStat is returned and if there is no Futility Boundary.}
#'                  \item{Delta}{Estimate of Delta (Difference from Control) for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. Required if Decision is not returned AND Futility Boundary scale is Delta or Isotonic Delta.}
#'                  \item{POCStatusArm}{Per-arm Proof of Concept status. Vector of Integers (0 or 1) having length the same as number of treatment arms. 1 = PoC threshold crossed for this arm, 0 = not crossed. Optional - Dose Finding only.}
#'                  \item{POCStatus}{Overall Proof of Concept status. Integer scalar (0 or 1). 1 = PoC threshold crossed overall, 0 = not crossed. Determined by highest dose arm. Optional - Dose Finding only.}
#'                  \item{AnalysisTime}{Optional Numeric scalar. Estimate of Analysis time. Same as look time for interims. Same as study duration for the final analysis.}
#'                  \item{OutList}{List or NULL. Pass-through list to next look for multi-look tracking. Optional.}
#'                  \item{ErrorCode}{Integer. Optional value \describe{
#'                                     \item{ErrorCode = 0}{No Error}
#'                                     \item{ErrorCode > 0}{Nonfatal error, current simulation is aborted but the next simulations will run}
#'                                     \item{ErrorCode < 0}{Fatal error, no further simulation will be attempted}
#'                                     }
#'                                     }
#'                      }
#' @details
#' Template for Dose Finding analysis R task.
#'
#' The function signature must remain unchanged. However, additional user-defined logic
#' and parameters may be incorporated through the UserParam list if needed.
#'
#' @keywords dose-finding analysis with continuous endpoint
######################################################################################################################## .

{{FUNCTION_NAME}} <- function( SimData, DesignParam, LookInfo = NULL, OutList, UserParam = NULL )
{
    nError            <- 0

    # Step 1: Read inputs

    # Step 2: Initialize output vectors
    nNumTrt           <- DesignParam$NumTreatments
    vDecision         <- rep( 0L, nNumTrt )
    vRawPVal          <- rep( NA_real_, nNumTrt )
    vTestStat         <- rep( NA_real_, nNumTrt )
    vDelta            <- rep( NA_real_, nNumTrt )
    vPOCStatusArm     <- rep( 0.0, nNumTrt )
    dOverallPOC       <- 0.0
    dEstAnalysisTime  <- NA
    lcurrOutList      <- list()

    # Step 3: Logic to compute Analysis Time

    # Step 4: Logic for Analysis for POC, futility and Efficacy

    # Step 5: Return the output list
    return( list( Decision     = as.integer( vDecision ),
                  RawPVal      = as.double( vRawPVal ),
                  TestStat     = as.double( vTestStat ),
                  Delta        = as.double( vDelta ),
                  POCStatusArm = as.integer( vPOCStatusArm ),
                  POCStatus    = as.integer( dOverallPOC ),
                  AnalysisTime = as.double( dEstAnalysisTime ),
                  OutList      = as.list( lcurrOutList ),
                  ErrorCode    = as.integer( nError ) ) )

}
