#  Last Modified Date: {{CREATION_DATE}}
#' @name {{FUNCTION_NAME}}
#' @title Analyze continuous outcome for dose finding design using Fixed Sequence Pairwise t-test.
#' @param SimData Data frame with subject data generated in current simulation with one row per patient. 
#'        It will have headers indicating the names of the columns. These names will be same as those used in 
#'        Data Generation. User should access the variables using headers, for example, SimData$ArrivalTime, 
#'        and not order. Optional outputs generated by Data Generation will also be available as columns of 
#'        this data frame. For analysis the most relevant variables are:
#'        \describe
#'        {
#'          \item{ArrivalTime}{A numeric value with the time the patient arrived in the trial}
#'          \item{TreatmentID}{An integer value specifying the index of arms to which subjects are allocated (one arm index per subject). Index for control is 0}
#'          \item{Response}{A numeric value for the continuous endpoint response value.}
#'          \item{CensorInd}{An integer value indicating whether the subject was censored or not.}
#'        }
#' @param DesignParam R List which consists of Design and Simulation Parameters which user
#'      may need to compute test statistic and perform test. User should access the variables
#'      using names for e.g., DesignParam$Alpha and not order. The items are as follows:
#'      \describe{
#'          \item{NumTreatments}{Integer. Number of Treatment arms (excluding control)}
#'          \item{Alpha}{Numeric. Type I Error (one-sided significance level)}
#'          \item{TailType}{Integer. Values are Left Tailed: 0, Right Tailed: 1}
#'          \item{VarType}{Integer. Variance Type. Values are Equal/Pooled: 4, Unequal/Welch: 5}
#'          \item{IsArmPresent}{Vector of integer flags indicating whether an arm is still present in the trial or was dropped in the interim. Length = number of treatment arms. Values are - Dropped in the interim: 0, Still present in the trial: 1}
#'          \item{MultAdjMethod}{Integer. Multiple Comparison Procedure. Values are Fixed Sequence Pairwise: 8}
#'          \item{RespLag}{Numeric. Follow up duration (optional)}
#'          \item{MaxCompleters}{Integer. Maximum Number of Completers.}
#'      }
#' @param LookInfo List Input Parameters related to multiple looks which user may need to compute test statistic
#'                 and perform test. User should access the variables using names,
#'                 for example LookInfo$NumLooks and not order. Other important variables are:
#'                 \describe{
#'                      \item{NumLooks}{An integer value with the number of looks in the study.}
#'                      \item{CurrLookIndex}{An integer value with the current index look, starting from 1.}
#'                      \item{CumCompleters}{Vector of Cumulative number of completers. Length = Number of looks.}
#'                      \item{FutBdryScale}{Integer. Futility boundary scale. Values are: Delta: 2, Isotonic Delta: 4, Z Scale: 0}
#'                      \item{FutBdry}{Vector of numeric futility boundaries. Length = Number of looks. Can be NA.}
#'                      \item{PoCScale}{Integer. Proof of Concept scale. Values are High Dose vs. Control: 0}
#'                      \item{PoCThreshold}{Numeric scalar. Proof of Concept threshold value.}
#' }
#' @param OutList List or NULL. Pass-through list from previous look (for multi-look tracking).
#'        Engine sets this to NULL for the first look. Supports Numeric/Integer/Character/List.
#'        Optional.
#' @param UserParam User can pass custom scalar variables defined by users as a member of this list.
#'                  User should access the variables using names, for example UserParam$Var1 and not order.
#'                  These variables can be of the following types: Integer, Numeric, or Character.
#'                  Optional.
#' @return The function must return a list in the return statement of the function. The information below lists 
#'             elements of the list, if the element is required or optional and a description of the return values if needed.
#'             \describe{
#'                  \item{Decision}{Vector of Integers or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. All other outputs become optional if Decision is returned. Values have the following meaning:
#'                                  \describe{
#'                                    \item{Decision = NA}{When the arm is dropped in a previous look}
#'                                    \item{Decision = 0}{when No boundary, futility or efficacy is crossed}
#'                                    \item{Decision = 1}{when the Lower Efficacy Boundary Crossed}
#'                                    \item{Decision = 2}{when the Upper Efficacy Boundary Crossed}
#'                                    \item{Decision = 3}{when the Futility Boundary Crossed}
#'                                    }
#'                                    }
#'                  \item{RawPVal}{p-Value computed from test statistics. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. All other outputs become optional if RawPVal is returned and if there is no Futility Boundary.}
#'                  \item{TestStat}{Value of appropriate Test Statistic on Wald (Z) scale for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. All other outputs become optional if TestStat is returned and if there is no Futility Boundary.}
#'                  \item{Delta}{Estimate of Delta (Difference from Control) for each Treatment Arm. Vector of Numerics or 'NA's having length the same as number of treatment arms. Arms dropped in a previous look should have value 'NA'. Optional value. Required if Decision is not returned AND Futility Boundary scale is Delta or Isotonic Delta.}
#'                  \item{POCStatusArm}{Per-arm Proof of Concept status. Vector of Integers (0 or 1) having length the same as number of treatment arms. 1 = PoC threshold crossed for this arm, 0 = not crossed. Optional - Dose Finding only.}
#'                  \item{POCStatus}{Overall Proof of Concept status. Integer scalar (0 or 1). 1 = PoC threshold crossed overall, 0 = not crossed. Determined by highest dose arm. Optional - Dose Finding only.}
#'                  \item{AnalysisTime}{Optional Numeric scalar. Estimate of Analysis time. Same as look time for interims. Same as study duration for the final analysis.}
#'                  \item{OutList}{List or NULL. Pass-through list to next look for multi-look tracking. Optional.}
#'                  \item{ErrorCode}{Integer. Optional value \describe{ 
#'                                     \item{ErrorCode = 0}{No Error}
#'                                     \item{ErrorCode > 0}{Nonfatal error, current simulation is aborted but the next simulations will run}
#'                                     \item{ErrorCode < 0}{Fatal error, no further simulation will be attempted}
#'                                     }
#'                                     }
#'                      }
#' @details
#' This function implements Fixed Sequence Pairwise testing for dose-finding studies with continuous endpoints.
#' The Fixed Sequence gatekeeping procedure tests hypotheses sequentially from the highest dose downward,
#' rejecting the null hypothesis only if the raw p-value is less than the total alpha. Once a hypothesis fails
#' to reject, all lower dose hypotheses are automatically rejected (futility cascade).
#'
#' Key Features:
#' - Pairwise t-tests comparing each treatment arm versus control
#' - Support for both equal and unequal variance assumptions
#' - Fixed Sequence multiple comparison procedure (inherently controls FWER)
#' - Multi-look capability with futility and efficacy boundaries
#' - Proof of Concept (PoC) threshold assessment
#' - Handles arm dropping and treatment selection
#'
#' Statistical Details:
#' - For equal variance (VarType=4): uses pooled variance with DOF = n_control + n_treatment - 2
#' - For unequal variance (VarType=5): uses Welch's t-test with Satterthwaite DOF approximation
#' - Right-Tail (TailType=1): P(T > t_stat) under H0
#' - Left-Tail (TailType=0): P(T < t_stat) under H0
#' @keywords dose-finding continuous fixed-sequence pairwise gatekeeping
#' @export
{{FUNCTION_NAME}} <- function( SimData, DesignParam, LookInfo = NULL, UserParam = NULL )
{
    nError            <- 0

    # If LookInfo is Null, then this is a fixed design and we use the DesignParam$MaxCompleters
    # Retrieve necessary information from the R objects. You may not need all the variables
    if(  !is.null( LookInfo )  )
    {
        nQtyOfLooks          <- LookInfo$NumLooks
        nLookIndex           <- LookInfo$CurrLookIndex
        nQtyOfPatsInAnalysis <- LookInfo$CumCompleters[ nLookIndex ]
        FutBdryScale         <- LookInfo$FutBdryScale
        FutBdry              <- LookInfo$FutBdry
        PoCScale             <- LookInfo$PoCScale
        PoCThreshold         <- LookInfo$PoCThreshold
        TailType             <- DesignParam$TailType
    }
    else
    {
        nQtyOfLooks          <- 1
        nLookIndex           <- 1
        nQtyOfPatsInAnalysis <- DesignParam$MaxCompleters
        FutBdryScale         <- NA
        FutBdry              <- NA
        PoCScale             <- NA
        PoCThreshold         <- NA
        TailType             <- DesignParam$TailType
    }
    
    # User must choose one from the following 3 options (Labelled Option 1, Option 2, Option 3) to create the analysis script.
    # Option 1 is the most flexible since it lets you setup your own Decision logic.
    # The other options allow you to partially customize the analysis logic while relying on East Horizon to do the rest of the computations.
    # Remember to delete the three return statements from the unused options. ####
    
    # ========================================================================
    # Option 1: Script returns Decision ####
    # ========================================================================
    # Use this option if you want to use your own decision rules.
    # This is the RECOMMENDED approach for Dose Finding analysis.

    # Extract parameters from DesignParam
    NumTrt       <- DesignParam$NumTreatments
    TotalAlpha   <- DesignParam$Alpha
    VarType      <- DesignParam$VarType
    IsArmPresent <- DesignParam$IsArmPresent

    # Initialize output vectors
    vDecision     <- rep(0L, NumTrt)
    vRawPVal      <- rep(NA_real_, NumTrt)
    vTestStat     <- rep(NA_real_, NumTrt)
    vDelta        <- rep(NA_real_, NumTrt)
    vPOCStatusArm <- rep(0.0, NumTrt)
    dOverallPOC   <- 0.0

    # Compute Analysis Time
    RespLag <- ifelse(!is.null(DesignParam$RespLag), DesignParam$RespLag, 0)
    CompletionTimes <- sort(SimData$ArrivalTime + RespLag)
    TargetCompleters <- LookInfo$CumCompleters[nLookIndex]

    if (!is.null(TargetCompleters) && !is.na(TargetCompleters) && 
        TargetCompleters <= length(CompletionTimes)) {
        dEstAnalysisTime <- CompletionTimes[TargetCompleters]
    } else {
        dEstAnalysisTime <- max(CompletionTimes, na.rm = TRUE)
    }

    # ---- CUSTOMIZE HERE: Your dose-finding analysis logic ----
    
    # Step 1: Identify active treatment arms
    SelectedArmIndex <- which(IsArmPresent == 1)
    
    if (length(SelectedArmIndex) == 0) {
        nError <- 1L
        return( list( Decision     = as.integer(vDecision),
                      RawPVal      = as.double(vRawPVal),
                      TestStat     = as.double(vTestStat),
                      Delta        = as.double(vDelta),
                      POCStatusArm = as.integer(vPOCStatusArm),
                      POCStatus    = as.integer(dOverallPOC),
                      AnalysisTime = as.double(dEstAnalysisTime),
                      OutList      = OutList,
                      ErrorCode    = as.integer(nError) ) )
    }

    # Mark dropped arms as NA in Decision
    DroppedArms <- which(IsArmPresent == 0)
    if (length(DroppedArms) > 0) {
        vDecision[DroppedArms] <- NA_integer_
    }

    # Step 2: Extract control data
    CtrlResp <- SimData$Response[SimData$TreatmentID == 0]
    nC    <- length(CtrlResp)
    meanC <- mean(CtrlResp)
    varC  <- var(CtrlResp)

    # Step 3: Fixed Sequence Pairwise Testing (Top-Down from Highest Dose)
    NumActive   <- length(SelectedArmIndex)
    CurrentArms <- SelectedArmIndex

    while (NumActive > 0) {
        # Highest dose arm under test
        TrtArmIndex <- CurrentArms[NumActive]

        # Compute pairwise results for all currently active arms
        pairwise_results <- list(
            RawPval  = numeric(NumActive),
            TestStat = numeric(NumActive),
            Delta    = numeric(NumActive)
        )

        for (j in seq_along(CurrentArms)) {
            k <- CurrentArms[j]
            TrtResp <- SimData$Response[SimData$TreatmentID == k]
            nT    <- length(TrtResp)
            meanT <- mean(TrtResp)
            varT  <- var(TrtResp)

            DeltaEst    <- meanT - meanC
            pairwise_results$Delta[j] <- DeltaEst

            # Compute variance and degrees of freedom
            if (VarType == 4L) {
                # Equal variance: pooled
                Sp2 <- ((nC - 1) * varC + (nT - 1) * varT) / (nC + nT - 2)
                SE  <- sqrt(Sp2 * (1/nC + 1/nT))
                dof <- nC + nT - 2
            } else {
                # Unequal variance: Welch
                vC  <- varC / nC
                vT  <- varT / nT
                SE  <- sqrt(vC + vT)
                dof <- round((vC + vT)^2 / (vC^2/(nC - 1) + vT^2/(nT - 1)))
            }

            # Compute test statistic and p-value
            if (SE < 1e-12) {
                pairwise_results$TestStat[j] <- 0.0
                pairwise_results$RawPval[j]  <- 1.0
            } else {
                tstat <- DeltaEst / SE
                pairwise_results$TestStat[j] <- tstat

                if (TailType == 1L) {
                    # Right-Tail: P(T > tstat)
                    pairwise_results$RawPval[j] <- pt(tstat, df = dof, lower.tail = FALSE)
                } else {
                    # Left-Tail: P(T < tstat)
                    pairwise_results$RawPval[j] <- pt(tstat, df = dof, lower.tail = TRUE)
                }
            }
        }

        # Store results for highest arm
        HighIdx <- NumActive
        vDelta[TrtArmIndex]    <- pairwise_results$Delta[HighIdx]
        vRawPVal[TrtArmIndex]  <- pairwise_results$RawPval[HighIdx]
        vTestStat[TrtArmIndex] <- pairwise_results$TestStat[HighIdx]

        # Fixed Sequence Decision Logic
        if (pairwise_results$RawPval[HighIdx] < TotalAlpha) {
            # EFFICACY: Reject null hypothesis for highest arm
            vDecision[TrtArmIndex] <- ifelse(TailType == 1L, 2L, 1L)

            # Remove this arm and continue with lower doses
            CurrentArms <- CurrentArms[CurrentArms != TrtArmIndex]
            NumActive   <- length(CurrentArms)

        } else {
            # NO EFFICACY: Check futility and cascade

            # Store results for remaining arms
            for (jj in seq_along(CurrentArms)) {
                arm <- CurrentArms[jj]
                if (is.na(vDelta[arm]))    vDelta[arm]    <- pairwise_results$Delta[jj]
                if (is.na(vRawPVal[arm]))  vRawPVal[arm]  <- pairwise_results$RawPval[jj]
                if (is.na(vTestStat[arm])) vTestStat[arm] <- pairwise_results$TestStat[jj]
            }

            # Check Futility Boundary (if applicable)
            HasFutility <- !is.null(FutBdry) && !all(is.na(FutBdry))

            if (HasFutility && !is.na(FutBdry[nLookIndex])) {
                FutBdryVal <- FutBdry[nLookIndex]

                for (jj in seq_along(CurrentArms)) {
                    arm <- CurrentArms[jj]
                    futility_hit <- FALSE

                    if (FutBdryScale %in% c(2L, 4L)) {
                        # Delta Scale: compare delta estimate against futility boundary
                        if (TailType == 1L) {
                            futility_hit <- (vDelta[arm] < FutBdryVal)
                        } else {
                            futility_hit <- (vDelta[arm] > FutBdryVal)
                        }
                    } else {
                        # Z Scale: compare test statistic against futility boundary
                        ts <- pairwise_results$TestStat[jj]
                        if (TailType == 1L) {
                            futility_hit <- (ts < FutBdryVal)
                        } else {
                            futility_hit <- (ts > FutBdryVal)
                        }
                    }

                    if (futility_hit && vDecision[arm] == 0L) {
                        vDecision[arm] <- 3L  # Futility
                    }
                }
            }

            # At final look: assign futility to all remaining arms without decision
            if (nLookIndex == nQtyOfLooks) {
                lowerArmIdx <- CurrentArms[CurrentArms <= TrtArmIndex]
                remaining   <- lowerArmIdx[vDecision[lowerArmIdx] == 0L]
                if (length(remaining) > 0) {
                    vDecision[remaining] <- 3L
                }
            }

            break  # Exit the while loop
        }
    }

    # Proof of Concept Assessment
    if (!is.null(PoCThreshold) && !is.na(PoCThreshold)) {
        ActiveForPoC <- which(!is.na(vDelta))

        if (length(ActiveForPoC) > 0) {
            iso_deltas <- pava_isotonic(vDelta[ActiveForPoC], TailType)

            if (TailType == 1L) {
                poc_arms <- which(round(iso_deltas, 7) > PoCThreshold)
            } else {
                poc_arms <- which(round(iso_deltas, 7) < PoCThreshold)
            }

            if (length(poc_arms) > 0) {
                vPOCStatusArm[ActiveForPoC[poc_arms]] <- 1L
            }

            HighestActiveArm <- max(ActiveForPoC)
            vPOCStatusArm[HighestActiveArm] <- ifelse(
                (TailType == 1L && iso_deltas[length(iso_deltas)] > PoCThreshold) ||
                (TailType == 0L && iso_deltas[length(iso_deltas)] < PoCThreshold),
                1L, 0L
            )
            dOverallPOC <- vPOCStatusArm[HighestActiveArm]
        }
    }

    # Prepare OutList for next look
    NewOutList <- list(
        PrevDecisions = vDecision,
        PrevDeltas    = vDelta,
        LookIndex     = nLookIndex
    )

    return( list( Decision     = as.integer(vDecision),
                  RawPVal      = as.double(vRawPVal),
                  TestStat     = as.double(vTestStat),
                  Delta        = as.double(vDelta),
                  POCStatusArm = as.integer(vPOCStatusArm),
                  POCStatus    = as.integer(dOverallPOC),
                  AnalysisTime = as.double(dEstAnalysisTime),
                  OutList      = NewOutList,
                  ErrorCode    = as.integer(nError) ) )
    
    
    # ========================================================================
    # Option 2: Script returns Raw p-value ####
    # ========================================================================
    # Use this option if you want to calculate the raw p-values with your own logic
    # but want to use the Decision generation logic of East Horizon.
    # NOTE: Delete this entire section if using Option 1.
    
    # vRawPVal <- 0
    # vDelta <- 0
    # # Setup raw p-value calculation logic
    # return( list( RawPVal = vRawPVal,
    #              Delta = vDelta,
    #              ErrorCode = as.integer(nError) ) )
    
    
    # ========================================================================
    # Option 3: Script returns Test Statistic ####
    # ========================================================================
    # Use this option if you want to calculate the test statistic with your own logic
    # but want to use the Decision generation logic of East Horizon.
    # NOTE: Delete this entire section if using Option 1.
    
    # vTestStat <- 0
    # vDelta <- 0
    # # Setup test statistic calculation logic
    # return( list( TestStat = vTestStat,
    #              Delta = vDelta,
    #              ErrorCode = as.integer(nError) ) )
    
}


# ==============================================================================
# HELPER FUNCTION: Isotonic Regression via PAVA
# ==============================================================================
#' @keywords internal
#' @description
#' Computes isotonic regression to enforce monotonicity on values using
#' the Pool Adjacent Violators Algorithm (PAVA).
#'
#' @param values numeric vector of values to be monotonized
#' @param tail_type integer — 0 = non-increasing, 1 = non-decreasing
#'
#' @return numeric vector of isotonic values (same length as input)
#'
#' @details
#' The PAVA algorithm iteratively pools adjacent blocks that violate the
#' monotonicity constraint, replacing each block with its weighted average.
#' Used for PoC assessment in dose-finding studies.
pava_isotonic <- function(values, tail_type)
{
    n <- length(values)
    if (n == 0) return(numeric(0))

    # For non-increasing (left-tail), negate values
    if (tail_type == 0L) values <- -values

    block_val <- values
    block_idx <- as.list(1:n)

    repeat {
        merged <- FALSE
        i <- 1
        while (i < length(block_val)) {
            if (block_val[i] > block_val[i + 1]) {
                # Merge blocks i and i+1 with simple average
                new_val <- mean(c(block_val[i], block_val[i + 1]))
                block_val[i] <- new_val
                block_val <- block_val[-(i + 1)]
                block_idx[[i]] <- c(block_idx[[i]], block_idx[[i + 1]])
                block_idx <- block_idx[-(i + 1)]
                merged <- TRUE
            } else {
                i <- i + 1
            }
        }
        if (!merged) break
    }

    # Reconstruct result vector
    result <- numeric(n)
    for (j in seq_along(block_val)) {
        result[block_idx[[j]]] <- block_val[j]
    }

    # Negate back if left-tail
    if (tail_type == 0L) result <- -result

    return(result)
}
